### ISSUE TITLE
How to generate sourcemaps?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/svelte-preprocess#140]
Hi @kaisermann, amazing project, thanks for your work!

In my Sapper project I have in rollup.config.js:

```js
...
const preprocessOptions = {
  scss: { includePaths: ['src', 'node_modules'] },
  postcss: {
    plugins: [
      autoprefixer,
      !dev && cssnano
    ].filter(plugin => plugin)
  }
}
const preprocess = autoPreprocess(preprocessOptions)
const sourcemap = process.env.GENERATE_SOURCEMAP || config.client.output().sourcemap

export default {
  client: {
    input: config.client.input(),
    output: { ...config.client.output(), sourcemap },
    plugins: [
      ...
      svelte({
        dev,
        hydratable: true,
        emitCss: true,
        preprocess
      }),
...
```

This create a good css in `__SAPPER__/build/main.[hash].css` but I need sourcemaps.

**Is there a way?**

I think I can use the below but I think I'm wrong.

```js
...
svelte({
  dev,
  hydratable: true,
  emitCss: true,
  css: css => css.write('dist/bundle.css', sourcemap), // <-- wrong directory and content
  preprocess
}),
...
```

**Comment by kaisermann** [comment]
Het @frederikhors 👋  Currently, the svelte compiler doesn't handle any sourcemap generated by preprocessors. There's a PR by @halfnelson that will add support for sourcemap sometime in the future. Whenever it lands, I guarantee will be passing sourcemaps down the pipeline 😁.

**Comment by frederikhors** [comment]
Please do not close this, as a remainder.

**Comment by kaisermann** [comment]
@frederikhors Sourcemaps are already generated if you have the appropriate option configured for your preprocessor, and are returned to the compiler. Don't worry, I'll make sure to create some tests to guarantee they are being returned. However, for now, there's nothing more we can do from this side. Waiting for: https://github.com/sveltejs/svelte/pull/5015.

**Comment by MingweiSamuel** [comment]
sveltejs/svelte#5015 -> sveltejs/svelte#5428 -> https://github.com/sveltejs/svelte/pull/5584  
for reference
