### ISSUE TITLE
inline import of .css file gets transformed to a generic css import

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/svelte-preprocess#141]
**Describe the bug**
In my project i'm trying to import normalize.css in to my _layout.svelte component. 
Instead of it getting impoted in to the main.css file it just adds the generic CSS import line instead.

![image](https://user-images.githubusercontent.com/12383587/80917009-8cfb2b80-8d5c-11ea-94b1-dec00689f72d.png)

```
<style lang="scss" global>
@import '@normalize.css/normalize.css';

/* some other random scss... */
</style>
```

**Logs**
None

**To Reproduce**
- clone the sapper template from the docs: https://sapper.svelte.dev/docs#Getting_started
- npm install normalize.css
- import it in to _layout.svelte in the src/routes folder

**Expected behavior**
Inline import it instead of having the generic css import line.

**Stacktraces**
None

**Information about your project:**

- Latest version of Edge (chromium)
- Windows 10
- 3.7.4
- Rollup

**Comment by UltraCakeBakery** [comment]
Just found out this is not unexpected behavior;
When I remove the .css extension from the import it can't find the file...

```
<style lang="scss" global>
@import '@normalize.css/normalize';
</style>
```

```
✗ server
File to import not found or unreadable: @normalize.css/normalize.
✗ client
File to import not found or unreadable: @normalize.css/normalize.
✔ service worker (9ms)
```

What am I doing wrong here?

**Comment by kaisermann** [comment]
Hey @UltraCakeBakery 👋 This seems related to how scss is handling that `@import` statement. Did you try using the `@use` statement? https://sass-lang.com/documentation/at-rules/use

**Comment by UltraCakeBakery** [comment]
Hey @kaisermann  👋
unless I'm doing something wrong @use also doesn't work;

```
<style lang="scss" global>
@use '@normalize.css/normalize';
@use '@normalize.css/normalize.css';
@use '../../node_modules/normalize.css/normalize.css';
</style>
```

![image](https://user-images.githubusercontent.com/12383587/80922826-d741d400-8d7f-11ea-8c28-8c8146b025a9.png)

I almost feel like it is not even considering it all to be SCSS but meanwhile nested classes and other stuff works perfectly fine.

**Comment by DominusVilicus** [comment]
@UltraCakeBakery having a similar issue https://github.com/kaisermann/svelte-preprocess/issues/146

**Comment by UltraCakeBakery** [comment]
@DominusVilicus I haven't found a fix yet. Kinda moved on to other problems. @kaisermann do you have any idea on what's going on?

**Comment by qwabra** [comment]
@kaisermann `@use` and global did't work!! :(

```html
<style lang="scss" global>
@use "@material/icon-button";
@use "@material/drawer";
@use "@material/list";
@include icon-button.core-styles;
@include drawer.core-styles;
@include list.core-styles;
</style>
```

**Comment by kaisermann** [comment]
@UltraCakeBakery Is this still happening to you? 

@qwabra this seems to be unrelated to the current issue. Besides that, if I'm not mistaken, `:global() { ... }` is wrong, as it should be `:global { ... }`.

**Comment by UltraCakeBakery** [comment]
> @UltraCakeBakery Is this still happening to you?
> 
> @qwabra this seems to be unrelated to the current issue. Besides that, if I'm not mistaken, `:global() { ... }` is wrong, as it should be `:global { ... }`.

Yes. It just dumbs the entire line in the css file. Doesn't matter if i use `@use` or `@import`

**Comment by benwoodward** [comment]
I resolved this issue in my codebase by using `atImport()`:

```js
// rollup.config.js
import sveltePreprocess from 'svelte-preprocess';
import atImport from 'postcss-import';

// snip

        preprocess: sveltePreprocess({
          sourceMap: !production,
          defaults: {
            style: 'scss'
          },
          sass: {
            includePaths: ['src'],
          },
          postcss: {
            plugins: [atImport({path: ['src/styles']})],
          },
        }),

// snip
```

What I think this is doing is inlining the CSS that's imported via an `@import` statement _before_ it's processed by Sass—So whatever bug is preventing `.css` files from being `@import`'ed into `<style lang="scss">` blocks is being circumvented.

**Comment by kaisermann** [comment]
@benwoodward The postcss transformer is the last one to be executed. It's working for you because you're importing a plain css file and the postcss plugin is handling that for ya.

**Comment by UltraCakeBakery** [comment]
Closing this as `@use` did the trick. I don't know why things didn't work before or what was going through my head. If I remember correctly `@import` is deprecated in postcss/scss anyways so this isn't weird behavior (i think?).

Thanks for the help anyways @kaisermann 👋
