### ISSUE TITLE
Are webpack loaders being invoked when importing css from a .svelte file?

### ISSUE THREAD

**Issue by onionhammer** [sveltejs/svelte-preprocess#147]
It seems like when preprocess/svelte/sapper run on a file the inline output that's produced does not execute any webpack loaders, so CSS is just copied + minified over without resolving url() references

**Comment by kaisermann** [comment]
Hey @onionhammer 👋  The `svelte-loader` is supposed to be writing the generated css for each component file as a `virtual file` which should be caught by `webpack`, check [here](https://github.com/sveltejs/svelte-loader/blob/master/index.js#L170). Can you share a repro if your issue happening?

**Comment by kaisermann** [comment]
Will close it for now. If the issue is still happening, feel free to reopen it!
