### ISSUE TITLE
pug on:click handler error

### ISSUE THREAD

**Issue by Gracrys** [sveltejs/svelte-preprocess#152]
Error when handling an on:click

```
<template type="pug">
div.my-8#genres
  +each('genres as genre')
    section.px-4.pb-4(id="{genre}")
      h2.text-left {genre}
      <!-- hr.mb-2 -->
      div.text-left
        +each('data[genre] as album')
          article( on:click='{player(album)}' )
              b {album.album}
              p {album.artist}
              i.subgenre {album.subgenre || ""}
              img(src="{album.cover}") 
</template>
```

that code doesnt works, the onclick runs for every iteration, and doesnt handle on click, but, when i pass no parameters to the  function, it works just on the event of the DOM 

i tried also {() => function()}

and didnt work either
marks a syntax error

i am using last version of all svelte, pug, svelte-preprocess and using an svelte-config

**Comment by kaisermann** [comment]
Hey @Gracrys 👋  Please don't erase the bug reporting template. Have you tried:

`article(on:click="{() => player(album)}")`?

Also, providing a reproducible example helps a lot 🙏

**Comment by Gracrys** [comment]
Hey, yeah, i tried using the other syntax and didnt work... i am doing all with html now

**Comment by PaHell** [comment]
This is my button:
`button(on:click="{(e) => setActive(e, i)}", class:active="{i === active}")`
_the function just prevents default and sets active = i_

The error I am getting says 'Unexpected Token' and points towards the function arrow "=>" which is shown as "=&gt;"

**Comment by PaHell** [comment]
@Gracrys Guess I'm just stupid, but I just paid close attention to the preprocessing readme and noticed, we just needed to add an exclamation mark before the attr value assignment. So it looks like this with an eventModifier
`button(on:click|preventDefault!="{() => value = !value}")`

**Comment by lewispham** [comment]
This ticket should be reopened as it's still an issue. It looks like pug is still trying to escape the syntax by replacing `>` with `&gt; `.

```
// svelte pug
on:click="{(evt) => userHandlers.signIn(evt)}"

// parsed html
on:click="{(evt) =&gt; userHandlers.signIn(evt)}"
```

**Comment by kaisermann** [comment]
@lewispham You're missing the `!` before the `=`:

`on:click="{(evt) => userHandlers.signIn(evt)}"`

should be

`on:click!="{(evt) => userHandlers.signIn(evt)}"`
