### ISSUE TITLE
Property 'typescript' does not exist on type 'HTMLProps<HTMLElement>'

### ISSUE THREAD

**Issue by hbbio** [sveltejs/svelte-preprocess#158]
**Describe the bug**

In vscode, when using `<script lang="typescript" src="../app/file.ts">`, the following error is raised:
```
Type '{ lang: string; typescript: true; }' is not assignable to type 'HTMLProps<HTMLElement>'.
  Property 'typescript' does not exist on type 'HTMLProps<HTMLElement>'.
```

Further errors are then raised.

**To Reproduce**

This seem to happen when a `<svelte:head>` tag is also present, which loads an external script.

I'll try to set up a minimal repo. What's the best starting repository using TypeScript for this?

**Expected behavior**
No error :)

**Information about your project:**

vscode 1.45.1
Svelte Beta 99.0.28
svelte-preprocess 3.7.4

**Comment by benmccann** [comment]
Do you get this when building on the command line? If yes, then I'd update it to explain that and remove references to vscode in this ticket. If not, then the ticket should be filed in `language-tools` as a vscode plugin bug

**Comment by hbbio** [comment]
Sorry @benmccann. `language-tools` seems to ask to file TS bugs here, so I was unsure about where to file the issue.

Build is fine.

**Comment by benmccann** [comment]
No worries! Glad you're testing this stuff out!
