### ISSUE TITLE
Cannot find module (without '.svelte' extension)

### ISSUE THREAD

**Issue by hbbio** [sveltejs/svelte-preprocess#160]
**Describe the bug**

Importing Svelte components without '.svelte' extension displays `Cannot find module` in vscode (using TypeScript).

Build is fine, using rollup with:
```
resolve({
      browser: true,
      extensions: [".svelte", ".ts", ".js"],
      dedupe: ["svelte"],
    }),
```

**To Reproduce**

Cf. https://github.com/hbbio/svelte-ts/commit/cf36d8a33d630b4c957dbd96a77d47c3993ff88d

**Expected behavior**

preprocess should resolve .svelte files (in addition to .ts and .js, cf #159 ).

**Information about your project:**

- svelte 3.23.0
- typescript 3.9.3
- svelte-preprocess 3.7.4
- rollup

**Comment by jasonlyu123** [comment]
this should be transferred to https://github.com/sveltejs/language-tools
