### ISSUE TITLE
typescript bundle size is too large

### ISSUE THREAD

**Issue by TimWillis** [sveltejs/svelte-preprocess#162]
**Describe the bug**
typescript build is to big  120k+

**To Reproduce**
Here is my webpack
`const devAndProd = [{
      entry: jsEntries,
      mode: 'production',
      devtool: "(none)",//https://webpack.js.org/configuration/devtool/
      output: {
        filename: '[name].prod.js',
        path: path.resolve('dist/public'),
        publicPath: '/'
      },
      optimization: {
        minimizer: [new TerserJSPlugin({}), new OptimizeCSSAssetsPlugin({})],
      },
      module: {
        rules: [
          {
            test: /\.ts?$/,
            use: [{
              loader: 'ts-loader',
              options: { transpileOnly: true,}
            }],
          },
          {
            test: /\.svelte$/,
            use: {
              loader: 'svelte-loader',
              options: {
                preprocess: require('svelte-preprocess')({ 
                  typescript: {
                    transpileOnly: true,
                    compilerOptions: {  
                      target: "esnext",
                      module: "esnext",
                    },
                  } }),
                emitCss: true,
                hydratable: true
              }
            }
          },
          {
            test: /\.css$/,
            use: [
               
               { loader: 'style-loader', options: { sourceMap: false } },
               { loader: 'css-loader', options: { sourceMap: false } },
            ]
          },
        ],
      },
      resolve: {
        alias: {
          svelte: path.resolve('node_modules', 'svelte')
        },
        mainFields: ['svelte', 'browser', 'module', 'main'],
        extensions: ['.mjs', '.js', '.svelte', '.ts',  '.js', '.json'],
        plugins: [new TsconfigPathsPlugin({ configFile: "./tsconfig.json" })], // allow us to use the `paths` property in tsconfig.json
      },
      plugins: [
        new MiniCssExtractPlugin({
          filename: (isDeploy ? '../functions/public/style/[name].css' : "style/[name].css"),
          chunkFilename: '[id].css'
        }),
        new webpack.DefinePlugin({
          'process.env': {
            name: JSON.stringify('prod'),
            referAFriendOffer: true,
          }
        })
      ],
    }];
`

**Expected behavior**
It seems to be including the sourcemaps in the bundle as it has -> 
sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiMC5qcyIsInNvdXJjZXMiO... characters going on for a long time

**Information about your project:**
node v13.7.0 
    "typescript": "^3.9.3",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11",
    "webpack-modules": "^1.0.0",
    "webpack-node-externals": "^1.7.2"

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
windows 10

- `svelte-preprocess` version (Please check you can reproduce the issue with the latest release!)
    "style-loader": "^0.23.1",
    "svelte": "^3.0.0",
    "svelte-loader": "2.13.3",
    "svelte-preprocess": "^3.7.4",

- Whether your project uses Webpack or Rollup
webpack

**Additional context**
I am using dynamic imports ie - but I don't think this is the issue...
`  function loadChatbox() {
    import('../../../../components/test.svelte').then(res => Chatbox = res.default)
  }`
Thanks for your help!

**Comment by dummdidumm** [comment]
As far as I know `svelte-preprocess` will honor the settings in your `tsconfig.json`, so if you set `"sourceMap": true` there, it will build source maps. If that is the case, you could overwrite these by adding a different config for prod.

**Comment by TimWillis** [comment]
I tried both true and false. Could it be svelte-loader and not the preprocessor? Here is my tsconfig ->
`{
    "compilerOptions": {
      "lib": [
        "dom",
        "dom.iterable",
        "esnext"
      ],      
      "target": "es2015",
      "module": "es2015",
      "typeRoots": ["node_modules/@types", "src/types"],
      "types": ["svelte"],    
      "allowJs": true,
      "skipLibCheck": true,
      "esModuleInterop": true,
      "allowSyntheticDefaultImports": true,
      "strict": true,
      "forceConsistentCasingInFileNames": true,
      "moduleResolution": "node",
      "resolveJsonModule": true,
      "isolatedModules": true,
      "suppressImplicitAnyIndexErrors": true,
      "downlevelIteration": true,
      "sourceMap": false,
      "outDir": "dist/",
      "baseUrl": ".",
      "paths": {
          "@types": ["src/types/*"], 
      }
    },
    "files" : [
         "src/types/types.d.ts"
    ],
    "include": ["src/index.ts",
      "node_modules/@bit/**/*"],
    "exclude": ["node_modues"]
  }`

**Comment by kaisermann** [comment]
Hey @TimWillis 👋  Please try again with the new `v4` version of the library. We're now only transpiling ts into js, the rest is up to your bundler.
