### ISSUE TITLE
Change order of node-sass, sass import

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/svelte-preprocess#163]
**Is your feature request related to a problem? Please describe.**
Over at the [language-tools](https://github.com/sveltejs/language-tools) repository we sometimes get error reports about using SCSS gives errors in the IDE. Most of the time it's because the users have `node-sass` installed and that is very sensitive to node versions. So if the IDE runs on a different node version than the user, it will likely crash if he does not set some configs, and even then it does not seem to work always. One suggestion we give the users is to use `sass` instead. Now the problem could be that users have installed `node-sass` globally and install `sass` locally just for that one project. This means, because `svelte-preprocess` tries to find `node-sass` first, the node module resolution algorithm would still find the global `node-sass` first and still throw the error about incompatible node versions. 

**Describe the solution you'd like**
If acceptably for you, I would like to change the order of lookups from `['node-sass', 'sass']` to `['sass', 'node-sass']`.

**Describe alternatives you've considered**
#149 seems to add an option to use a specific compiler, that could help, too. 

**How important is this feature to you?**
Not super important because there are workarounds, but it would still help us.

**Comment by kaisermann** [comment]
Hey @dummdidumm 👋 Yeah, I'm interested in changing it. In fact, I tried in #151 but started to get some errors regarding `@import`s not being able to resolve their paths. I'll merge #149 soon (with the option `implementation` instead of `compiler`), but I'd also like to require `sass` first, I just didn't manage to get what was happening with the tests.

**Comment by kaisermann** [comment]
@dummdidumm Just released `v3.8.0` with the `implementation` prop! I'll try reordering the sass lookup again anyway 😁

**Comment by kaisermann** [comment]
When I switch from `node-sass` to `sass` I start getting this error:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/12702016/83910965-d2d35700-a741-11ea-88c9-f86b79ba87cd.png">

Already tried to debug it, but I've hit a wall.

**Comment by dummdidumm** [comment]
Now that the `implementation` prop is implemented, could you use that in the tests to hardcode it to use `node-sass` so it works like before?

**Comment by kaisermann** [comment]
Will be changed in `v4` 😁
