### ISSUE TITLE
PaperScript

### ISSUE THREAD

**Issue by tonyketcham** [sveltejs/svelte-preprocess#165]
### Feature requests and proposals

I've been working with [Paper.js](http://paperjs.org/) in Svelte and have been wanting to take advantage of Paper's included [PaperScript](http://paperjs.org/tutorials/getting-started/working-with-paper-js/#what-is-paperscript) & [preprocessor](http://paperjs.org/reference/paperscript/) so I can abstract some complexity out of my Paper projects.

I know this is probably a niche desire, so this is not necessarily a feature request but more so a question geared towards the most knowledgable minds on preprocessing languages for Svelte. Therefore, I was thinking of forking this project as a dedicated PaperScript preprocessor for Svelte rather than asking it be included here. 

What I'm essentially asking for are recommendations on how I should go about implementing PaperScript's preprocessor with this project to seamlessly add support via something like a `<script type="text/paperscript">` tag. I've dug through some of the source on here but I'm not exactly sure where to start. Any help would be immensely appreciated!

**Comment by tonyketcham** [comment]
For quick reference, here's [PaperScript's preprocessor source](https://github.com/paperjs/paper.js/blob/db82f41151be5cd4a347ab368ac093c633551acf/src/core/PaperScript.js). Would I just need to mimic how Svelte Preprocess handles CoffeeScript? 

Another point I've thought on a bit more -- since the installation of this project is completely modular, would a PaperScript module be worth including just for the hell of it even if there may not be a vast crowd of users?

**Comment by kaisermann** [comment]
Hey @tonyketcham! You don't actually need this library to create a simple processor for `paperscript`! You would just need to pass an object to your `preprocess` property:

```js
const myPreprocessor = {
  script({ content }) {
    return { code: paperscript.compile(content) }
  }
}
...
{
  preprocess: [myPreprocessor]
}
```

However, if you want to use attributes to control what language you're using, `svelte-preprocess` allows you to define custom processors by just defining a function with the name of the language:

```js
import autoProcess from 'svelte-preprocess'
...

const preprocess = autoProcess({
  // this is going to be executed only for `<script lang="paperscript">`
  // or `<script type="text/paperscript">
  paperscript({ content, filename, attributes }) {
    return { code: paperscript.compile(content) }
  }
})
...
{
  preprocess: preprocess
}

I couldn't actually find how to use the `paperscript` compiler on my quick research, but that's the gist of how to use it. Since it's (supposedly) simple to add a new small processor, I don't think we should add this to the library for now. If more people find it useful we can rethink this 😁.
