### ISSUE TITLE
Handle non-existing styles more gracefully

### ISSUE THREAD

**Issue by illright** [sveltejs/svelte-preprocess#166]
**Describe the bug**
Currently, `<style src="doesnt/exist.scss"></style>` will compile into `<style src="doesnt/exist.scss">undefined</style>`, which crashes the Svelte style parser. It would be nice to handle such situations by simply creating an empty style tag, emitting an error message in the console, that way at least the server runs.

**To Reproduce**
* get a fresh [Svelte app template](https://github.com/sveltejs/template)
* install `svelte-preprocess` and `node-sass`
* add `autoPreprocess` to `rollup.config.js`
* in `src/App.svelte`, remove the content of the `<style>` tag and add `src="doesnt/exist.scss"`
* run the development server

**Expected behavior**
The server should run without crashing, warning the developer about the error.

**Additional context**
Not sure if the same problem persists with other style processors and other script or markup processors, for that matter. Also not sure if this is intended behaviour.

The reason for this request is that in some cases, crashing a server makes Rollup lose track of dependencies, not rebuilding even after one fixes the faulty path

**Comment by kaisermann** [comment]
Hey @illright 👋 Thanks for the report. Silly mistake from my part 😁   

Fixed in `v3.9.2` 🎉
