### ISSUE TITLE
 preprocessor for SVG consideration?

### ISSUE THREAD

**Issue by lightingland** [sveltejs/svelte-preprocess#169]
try some svg solutions and found it kind needed in preprocessor. full features of svg tag need to be done, like attributes.

**Comment by kaisermann** [comment]
Hey @lightingland 👋  Please don't remove the feature request template. I couldn't grasp what you're needing. Can you fill the template with examples? Thanks!

**Comment by lightingland** [comment]
Right now I am using solution from rollup-plugin-svg-import and it handle svg like this:
`import fab_google from './logo.svg'`
`     <div class='w-6h-6'>`
` {@html logo} `
`      </div> `
the con is I lost everything that `<svg>` tag should have.
and I think svg could handle like a real svelte component
`<script>`
 `	import logo from"./logo.svg";`
`</script>`
`<logo width="20" class="text content" fill="red" the rest things go here />`

**Comment by kaisermann** [comment]
@lightingland Would it only include the SVG markup in your component? I'm not remembering clearly if we can freely put svg inside svelte components. How do you imagine the usage?

Example:

```svelte
<script>
  import logo from './logo.svg'
</script>

<div class='w-6h-6'>
  {logo}
</div>
```

**Comment by kaisermann** [comment]
@lightingland If you want to pass props to your svg, I'd suggest wrapping each svg inside a `.svelte` component and delegate its props to the svg itself.
