### ISSUE TITLE
Display a warning when a file from src cannot be resolved

### ISSUE THREAD

**Issue by illright** [sveltejs/svelte-preprocess#174]
**Is your feature request related to a problem? Please describe.**
If one accidentally mistypes the URL to an external file, they'll only notice it when the usage of that file will fail. For instance, for stylesheets, it is particularly hard to notice.

**Describe the solution you'd like**
Whenever a resolution of an external file fails, print an error to the console.

**Describe alternatives you've considered**
Failing with an error upon failed resolution, but that's not very handy, especially if we're talking about typos which are fixed soon afterwards.

**How important is this feature to you?**
Not really a life-and-death matter, but would be nice to have and might be relatively simple to implement.

**Comment by kaisermann** [comment]
Hey @illright 👋  Sorry for taking so long to answer! It makes complete sense to make it a clearer when a `src` file is not found. I added a simple `console.warn` to `v3.9.11` 😁
