### ISSUE TITLE
Remove type-checking from the `typescript` transformer

### ISSUE THREAD

**Issue by kaisermann** [sveltejs/svelte-preprocess#178]
As https://github.com/sveltejs/language-tools keeps evolving and we now have a working type-checker, I think `svelte-preprocess` should only care about **transpiling** typescript code. Not only this would speed up the process, it would remove a LOT of code from the codebase.

This isn't a BREAKING CHANGE per se, but it could break some expectations, so this would be done only in the next major version.

Edit:

This can be a breaking change because `tsc` won't resolve type `import`s anymore, so you'd need to use `import type` instead. Seems okay to me, but would definitely like to hear some feedback first.

**Comment by Martaver** [comment]
Imho this is a reasonable compromise, most tooling seems to prefer running type checking in a separate process or in the IDE. How users consume their type checking is a matter of taste and varies greatly. Svelte doesn't need to have a say in that.

**Comment by Martaver** [comment]
Also relevant, there is a beta version of a project-level type analysis feature for vscode which seems largely powered by tsserver. Issue here: https://github.com/microsoft/vscode/issues/13953

**Comment by rsheasby** [comment]
Excuse my ignorance, but does the preprocessor not already use tsc to do the transpilation? I don't understand why removing type checking from the preprocessor would even be possible, or why it would result in less code? 

Either way, as a user of svelte with typescript I disagree with removing type checking from the build process. In my mind the main advantage of typescript over javascript with jsdoc annotations is that the build process removes a large class of bugs by performing type checking. I may be misunderstanding, but if the implementation of this issue would result in type checking being completely removed from the build process for TS script tags, I wouldn't be in favour of it.

I get that type checking in the language server does provide a lot already, but I'd still need a practical way to do type checking as part of automated testing/CI.

**Comment by kaisermann** [comment]
@rsheasby I understand your concern! However, you'll be able to type-check your files with `svelte-check`. You just need to add it to your pipelines as you'd do with `eslint` or similar tools.

The typescript compiler doesn't have support for transpiling AND type-checking content from memory, but it does support only transpiling it. When I added type-checking to this lib, we didn't have any other tool (apart from other ts preprocessors) available. If you take a look at the open issues related to `typescript` with `svelte` syntax, you can see there's a LOT of edge cases. `svelte-check` takes a different approach, which uses the language-server with a combination of transforming your svelte components into plain `jsx`, making type-checking work as expected. It even works with variables used in the markup, for example.

When I say "remove type-checking", I mean to only transpile TS => JS, without caring about the types and let a proper tool handle it.

**Comment by kaisermann** [comment]
v4 is out and we're no long doing any kind of type-checking. You can check the migration guide to see how to properly type-check your components.
