### ISSUE TITLE
Template tag in non-auto mode can be set to anything

### ISSUE THREAD

**Issue by samsour** [sveltejs/svelte-preprocess#179]
Hi there!
I want to use a custom template tag. The preprocess is not in auto mode as I need other options configured.

**Problem:**
The option _markupTagName_ won't listen to the assigned value set in the preprocess options.
I am using the rollup config and it looks like:
```
preprocess: sveltePreprocess({
	markupTagName: 'markup',
	scss: {
		data: '@import "./src/style/main.scss";'
	},
	...
}),
```

Example component:
```
<script>...</script>

<anything>
	<h1>Hello world!</h1>
</anything>
```

**Expected behavior**
Wrapped markup/template code will only be allowed inside of a <markup></markup> tag.
Instead the content can be inside of <anything> or <weirdMarkupTagName> template tags.

I just wondered if this a bug or a feature.

**Comment by kaisermann** [comment]
Hey @samsour 👋 ! Sorry, but I didn't understand your question. Are you trying to change the `markup tag` to `markup` and it's not working? Can you share a repro In your example you set it to `markup` but used `anything`.

**Comment by samsour** [comment]
Thank you @kaisermann for the response. Yes my last sentence makes no sense at all...

I set the markupTagName to 'markup'.
Templating code can now be inside of <markup></markup>. But ALSO inside of <anythingelse> or <blablabla>.

So my thought was that preprocess won't listen to the exact string that is assigned to markupTagName. It seems like anything can be in the tag that wraps the markup code in a svelte component.

I'll try to post something to reproduce it.

**Comment by kaisermann** [comment]
Oh I see! The `<markup>` tag is only a way to use a preprocessor ONLY for your markup, like `pug` without having to type the whole component in it (including `style` and `script` tags).

```
<markup lang="pug"> ... </markup>
```

If `svelte-preprocess` doesn't find your `<markup>` tag, it doesn't do anything and svelte handles that `<anythingelse>` as it would with any other tag.
