### ISSUE TITLE
VS Code trouble with new CSS feature

### ISSUE THREAD

**Issue by koddr** [sveltejs/svelte-preprocess#180]
**Describe the bug**
I faced some trouble with new CSS syntax feature for `@media (width >= 768px) {...}` ([Media Queries Level 4](https://drafts.csswg.org/mediaqueries/#mq-range-context)) at VS Code on Svelte component. I use latest Sapper version:

```
    // ...
    "sapper": "^0.27.15",
    "svelte": "^3.23.2"
}
```

And Svelte linter always show me this error:

![Screenshot 2020-06-12 at 13 32 35](https://user-images.githubusercontent.com/11155743/84502071-58b24d80-acc0-11ea-90d1-4c64e0eaf3a4.png)

Also, I see this error at normal `*.css` files, but if I disable VS Code CSS validation (by setting `css.validate: false` in settings) this error gone.

How to solve or disable this error? 🤔 

**Information about your project:**

VS Code version:

```
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

- Your browser and the version: FireFox 77
- Your operating system: macOS 10.14.6
- `svelte-preprocess` version 3.9.7
- Rollup

**Additional context**
No.

**Comment by kaisermann** [comment]
You can set the "svelte.plugin.css.diagnostics.enable` option to `false` to disable the css validation. However, for the svelte compiler to be able to understand that syntax, you'll need to pass your component css through a preprocessor that handles it, like `postcss` with `postcss-preset-env`.

**Comment by koddr** [comment]
@kaisermann hi! Thanks for reply, but it's not (_fully_) works. 

VS Code CSS validation is gone after I set `svelte.plugin.css.diagnostics.enable` to `false`, but I still see `css-syntax-error` message by Svelte:

![Screenshot 2020-06-13 at 13 04 54](https://user-images.githubusercontent.com/11155743/84566074-01bb7f80-ad77-11ea-914b-3d23d0a9d98b.png)

```console
Colon is expected. If you expect this syntax to work, here are some suggestions: 
If you use less/SCSS with `svelte-preprocessor`, did you add `lang="scss"`/`lang="less"` 
to you `style` tag? If you use SCSS, it may be necessary to add the path to your NODE 
runtime to the setting `svelte.language-server.runtime`, or use `sass` instead of `node-sass`.
Did you setup a `svelte.config.js`? See https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode#using-with-preprocessors 
for more info.svelte(css-syntax-error)
```

There may be a way to tell `svelte-preprocess` to support new CSS syntax in `*.svelte` files?

**Comment by kaisermann** [comment]
You can use https://preset-env.cssdb.org/features#media-query-ranges`:

```js
{
  ...
  preprocess: preprocess({
    postcss: {
      plugins: [require('postcss-preset-env')]
    }
  })
  ...
}
```

(Didn't test it, but it should be something similar)

[Make sure to have a `svelte.config.js` with your preprocess config so the `svelte` stop complaining about your syntax.](https://github.com/sveltejs/svelte-preprocess#with-svelte-vs-code)

**Comment by MrinmoyHaloi** [comment]
Hey, I am having the same problem. But the feature is supported by most browsers now days. Shouldn't it be implented in the css preprocessor directly ? @kaisermann
