### ISSUE TITLE
Typescript does not understand reactive expressions with strictNullChecks

### ISSUE THREAD

**Issue by dbrgn** [sveltejs/svelte-preprocess#181]
**Describe the bug**

The following component fails to typecheck when `strictNullChecks` is enabled.

```typescript
<script lang="typescript">
    let foo: string | null = null;

    $: if (foo !== null) {
        // Condition may become valid at runtime
        console.log('String length: ' + foo.length);
    }
</script>
```

TypeScript thinks it can be sure that `foo` is always null (because it has been assigned null just before the `!== null`) check. It therefore determines the `foo` type within the `if` expression to be the never type.

```
Main.svelte:6:41 - error TS2339: Property 'length' does not exist on type 'never'.

6     console.log('String length: ' + foo.length);
                                          ~~~~~~
```

The reason is that TypeScript does not understand that `$: expression` may be re-evaluated at a later point in time.

**To Reproduce**

Repro: https://github.com/dbrgn/ts-preprocess-repro

**Information about your project:**

- OS: Arch Linux
- `svelte-preprocess` 3.9.7 (with Webpack)

**Comment by kaisermann** [comment]
Hey @dbrgn 👋  This is another reason for #178. Unfortunately we can't make the typescript compiler support every svelte quirk. I'm more inclined to just transpile the code as it is and leave the type-checking to a tool made for that (like `svelte-check`).

**Comment by dbrgn** [comment]
As long as there is proper support for type checking, that would be fine for me.

**Comment by kaisermann** [comment]
`v4` is out and we're no long doing any kind of type-checking. You can check the [migration guide to see how to properly type-check your components](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/migration-guide.md#type-checking-components).

**Comment by dbrgn** [comment]
Thanks for the update!
