### ISSUE TITLE
Typescript compile errors don't cause build failure

### ISSUE THREAD

**Issue by rsheasby** [sveltejs/svelte-preprocess#182]
**Describe the bug**
When using svelte-preprocess for typescript, a TS compilation error does not abort the build, and results in the bundle still being created, as well as a successful status code being returned.

This is especially a problem for verifying that something builds correctly in CI scripts.

**Logs**
You can see an example here with a syntax error in a typescript style tag:
<details>
<pre>
rsheasby@Ryan-Mac ~/D/b/client (6-registration-email)> npx rollup -c

src/main.js → public/build/bundle.js...
src/App.svelte:7:14 - error TS1005: '=' expected.

7 import Bulma ;from './Bulma.svelte';
               ~
src/App.svelte:7:15 - error TS2304: Cannot find name 'from'.

7 import Bulma ;from './Bulma.svelte';
                ~~~~
src/App.svelte:7:20 - error TS1005: ';' expected.

7 import Bulma ;from './Bulma.svelte';
                     ~~~~~~~~~~~~~~~~

created public/build/bundle.js in 8s
rsheasby@Ryan-Mac ~/D/b/client (6-registration-email)> echo $status
0
</pre>
</details>

As you can see, the bundle is still written and the status code is 0.
When doing the same build with a javascript style tag(thereby removing the preprocess step), the build fails and returns status code 1 as expected.

**To Reproduce**
Setup boilerplate svelte with rollup, add svelte-preprocess for typescript, and add a syntax error to a typescript script tag.

**Expected behavior**
Rollup should fail and return a bad status code when a preprocessor fails

**Information about your project:**
Examples provided from macOS Catalina with rollup v2.16.11 and svelte-preprocess v3.9.7.
Has been confirmed on various Linux systems too.

**Comment by kaisermann** [comment]
Hey @rsheasby 👋  Thanks for the report! It does indeed make sense to throw an error if the ts compiler finds some error. I've added it to `v3.9.9` 🎉

**Comment by ansavchenco** [comment]
Looks like the issue is still present in `4.6.1` when Snowpack is used as a bundler.

**Comment by dubiousandrew** [comment]
I have this issue with 4.5.2 and just upgraded to 4.6.5 and still have this problem.

**Comment by kaisermann** [comment]
@dubiousandrew Are you also using Snowpack?

**Comment by jbrunton** [comment]
@kaisermann: I'm seeing this with the default Svelte typescript template, using Rollup. Example repo here: https://github.com/jbrunton/svelte-ts-error-example/

Repo was created like so:

```
npx degit sveltejs/template svelte-ts-error-example
cd svelte-ts-error-example
node scripts/setupTypeScript.js
```

Then I added a line to main.ts which doesn't type check.

Build output:

```
npm run build

> svelte-app@1.0.0 build /Users/john/git/svelte-ts-error-example
> rollup -c


src/main.ts → public/build/bundle.js...
(!) Plugin typescript: @rollup/plugin-typescript TS2322: Type 'string' is not assignable to type 'number'.
src/main.ts: (10:7)

10 const x: number = "1";
         ~

(!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
created public/build/bundle.js in 1.2s
$ echo $?
0
```

`svelte-preprocess` version is the latest (4.7.2).

**Comment by ItzaMi** [comment]
Hey 👋 Created a new project on Svelte following the steps on the homepage:
```
npx degit sveltejs/template my-svelte-project
node scripts/setupTypeScript.js

yarn
yarn run dev
```

And I get TypeScript errors on my code but on build (or even on `yarn run dev`) I have no error messages. What might be happening here?
`sourceMap` is set to `true`

**Comment by kaisermann** [comment]
> @kaisermann: I'm still seeing this with the default Svelte typescript template, using Rollup. Example repo here: https://github.com/jbrunton/svelte-ts-error-example/
> 
> Repo was created like so:
> 
> ```
> npx degit sveltejs/template svelte-ts-error-example
> cd svelte-ts-error-example
> node scripts/setupTypeScript.js
> ```
> 
> Then I added a line to main.ts which doesn't type check.
> 
> Build output:
> 
> ```
> npm run build
> 
> > svelte-app@1.0.0 build /Users/john/git/svelte-ts-error-example
> > rollup -c
> 
> 
> src/main.ts → public/build/bundle.js...
> (!) Plugin typescript: @rollup/plugin-typescript TS2322: Type 'string' is not assignable to type 'number'.
> src/main.ts: (10:7)
> 
> 10 const x: number = "1";
>          ~
> 
> (!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
> created public/build/bundle.js in 1.2s
> $ echo $?
> 0
> ```
> 
> `svelte-preprocess` version is the latest (4.7.2).Ï

This is expected since we don't do any kind of type-checking. Your TS code is just transpiled to JS. 


> Hey 👋 Created a new project on Svelte following the steps on the homepage:
> 
> ```
> npx degit sveltejs/template my-svelte-project
> node scripts/setupTypeScript.js
> 
> yarn
> yarn run dev
> ```
> 
> And I get TypeScript errors on my code but on build (or even on `yarn run dev`) I have no error messages. What might be happening here?
> `sourceMap` is set to `true`


Hey, @ItzaMi 👋  I couldn't reproduce it with the commands that you typed.

**Comment by kaisermann** [comment]
We won't be throwing type-related errors as we only transpile TS code into JS.

**Comment by soanvig** [comment]
So is there any solution to this? It basically just throws away half of the benefits of TS

**Comment by soanvig** [comment]
I'm using webpack 5.45.1, preprocess 4.7.4 and svelte 3.23.2

I don't understand You @kaisermann , you said:

>  Thanks for the report! It does indeed make sense to throw an error if the ts compiler finds some error. I've added it to v3.9.9 🎉

and later on

> We won't be throwing type-related errors as we only transpile TS code into JS.

Currently I have no errors thrown, and builds succeeds even if there is TS error in Svelte component. Therefore I lose primary reason why one installs TS in the first place.
