### ISSUE TITLE
Typescript preprocessor Ignores all config except "compilerOptions"

### ISSUE THREAD

**Issue by n0th1ng-else** [sveltejs/svelte-preprocess#187]
**Describe the bug**
Sometimes you want to declare a global variable (which may be injected by webpack DefinePlugin) and use it in the code. Usually, it can be achieved by creating a new declaration file in the root and declaring stuff in the global module. After this, we use tsconfig.json -> `files` property (or `include` also work) to define that file along with other modules in the project.
svelte-preprocess ignores all tsconfig properties except `compilerOptions` data so it throws the error that (in my case) `runtime` variable is not defined

**Logs**
Looks like this
```
src/helpers/runtime.ts:8:12 - error TS2304: Cannot find name 'runtime'.

8     return runtime.isProduction;
             ~~~~~~~

```

**Expected behavior**
to pick `files`, `include` properties with and pass them to typescript compiler.

**Information about your project:**
- webpack
- svelte-preprocess 3.9.9

a standard way to describe global data in typescript is to have `types.ts` in the root (or it might be `types.d.ts`)

```
declare global {
	let runtime: {
                isProduction: boolean;
        }
}
```

considering that some tool injects that global var. For example in webpack:
```
	plugins: [
		new webpack.DefinePlugin({
			runtime: JSON.stringify({
				isProduction: true,
			})
		}),
```

and then in tsconfig.json
```
{
	"compilerOptions": {
.........
	},
        "files": ["./types.ts"]
}

```

**Comment by kaisermann** [comment]
Hey @n0th1ng-else 👋  From `v4` onward, `svelte-preprocess` will only transpile ts to js. Type checking should be done with the vscode/atom/etc extension + `svelte-check`: https://github.com/sveltejs/svelte-preprocess/blob/master/docs/migration-guide.md#type-checking-components
