### ISSUE TITLE
Sass preprocessor data field does not prepend the string given to it

### ISSUE THREAD

**Issue by MartonDev** [sveltejs/svelte-preprocess#188]
**Describe the bug**
Using the data field, I tried prepanding an import to a sass file, but it does nothing. The path I gave it should work, because when I console log it, copy it and paste it to the style tag, in a component, it works.

**Logs**
```sh
bundles src/main.js → public/build/bundle.js...
[!] (plugin svelte) Error: Undefined variable: "$primary-color".
src/views/Test.svelte
Error: Undefined variable: "$primary-color".
    at options.error (/home/marton/Desktop/Node/Svelte-starter-kit/node_modules/node-sass/lib/index.js:291:26)
```
If I console log the data field, I get this (which is the path I expected): 
```sh
@import '/home/marton/Desktop/Node/Svelte-starter-kit/src/sass/_variables.sass'
```
And this works if I put it to a component, so the path is okay, it just does not get prepanded

**To Reproduce**
Put this in `rollup.config.js`, in the `svelte({})` function in the `plugins` array:
```js
preprocess: [

    sass({

        data: `@import '${ join(process.cwd(), 'src/sass/_variables.sass') }'`

    })

]
```
Or see this commit tree on my repo: https://github.com/MartonDev/Svelte-starter-kit/tree/0f17b4138bc8dcf9b2474d405d856b7b0866accd

**Expected behavior**
The preprocess should prepand the data before all `<style>` tags in components.

**Information about your project:**

- Your browser and the version: Brave 1.9.68 (Chromium: 81.0.4044.138)

- Your operating system: Manjaro Linux (kernel 5.4.40-1-MANJARO)

- `svelte-preprocess` version: `"^3.9.9"` (latest)

- Whether your project uses Webpack or Rollup: **Rollup**

**Comment by mlbiche** [comment]
Same here !

When appending `@use "theme" as *;` directly into my file, my compilation does not trigger any error. But when using the `data` field, I have an undefined variable error.
I have tried :
* `data: '@use "theme" as *;'`
* `data: '@use "src/styles/theme" as *;'`
* ```data: `@use "${join(process.cwd(), 'src/styles/_theme.scss')}" as *;` ```
But none of them works...

**Comment by MartonDev** [comment]
Might not be the same issue, because for me, it's not prepanding the data and gives no error even if I try entering a path that doesn't exist

**Comment by kaisermann** [comment]
Hey @MartonDev 👋 

You're accidentally importing the automatic preprocessor (the default export). Change 

`import sass from "svelte-preprocess";`

to 

`import { sass } from "svelte-preprocess";` and you should be good to go!

**Comment by kaisermann** [comment]
@mlbiche Can you share a repro?

**Comment by mlbiche** [comment]
@kaisermann You can check it on this branch of my project: https://gitlab.com/mlbiche/izard-app/-/tree/sapper-init
All the SCSS related code has been committed here : https://gitlab.com/mlbiche/izard-app/-/commit/ddbeb5b4a364027cbefefe26f3c691cd91e108d0
I have tried updating from automatic svelte-preprocessing with config to standalone svelte-preprocessors, but it does not change anything. Here is the code update :

```javascript
  preprocess: sveltePreprocess({
    scss: {
      includePaths: ['src/styles'],
      data: '@use "theme" as *;',
      implementation: require('sass'),
      renderSync: true
    }
  })

// Updated to

  preprocess: [
    sass({
      includePaths: ['src/styles'],
      data: '@use "theme" as *;',
      implementation: require('sass'),
      renderSync: true
    }),
    globalStyle()
  ]
```

Do you want me to create a new issue ?

**Comment by MartonDev** [comment]
> Hey @MartonDev 
> 
> You're accidentally importing the automatic preprocessor (the default export). Change
> 
> `import sass from "svelte-preprocess";`
> 
> to
> 
> `import { sass } from "svelte-preprocess";` and you should be good to go!
> 
> edit: just found a bug when using `sass` syntax with the standalone processor. Fixed in `3.9.10`

Great :) The update and changing the import fixed it
Thank you for such an amazing project :D

**Comment by kaisermann** [comment]
@mlbiche That is happening because `svelte-preprocess` only prepends the `'@use "theme" as *;',` to the component's scss. `global.scss`, `background.scss` and `button.scss` don't know about that prepended content.

**Comment by mlbiche** [comment]
@kaisermann Got it, thank you for your help !
