### ISSUE TITLE
Multiple imports with index.ts

### ISSUE THREAD

**Issue by daarxwalker** [sveltejs/svelte-preprocess#190]
**Describe the bug**
Multiple imports have to be index.js, but when it's index.ts, not working.

**Logs**
```text
• client
/Users/daar/Documents/Projects/sapper-with-ts-sample/src/routes/index.svelte
'Button' is not defined
31: <p>{how ? 'Daar' : 'Dont know'}</p>
32: <button on:click={handleClick}>Test click</button>
33: <Button>Test</Button>
    ^
34: 
• server
/Users/daar/Documents/Projects/sapper-with-ts-sample/src/routes/index.svelte
'Button' is not defined
31: <p>{how ? 'Daar' : 'Dont know'}</p>
32: <button on:click={handleClick}>Test click</button>
33: <Button>Test</Button>
```

**To Reproduce**
If you want to do multiple imports, you can't do this with index.ts in folder, you have to use index.js, although preprocess should know TypeScript.

**Expected behavior**
I want to have index.ts, not index.js for multiple imports.

**Stacktraces**

index.svelte
```javascript
import { Button } from '../components/core'
```

index.ts
```javascript
import Button from './Button.svelte'

export {
    Button
}
```

</details>

**Information about your project:**

- Your operating system: macOS Catalina 10.15.5

- `svelte-preprocess` version ^3.9.8

- Sapper, Rollup

**Comment by kaisermann** [comment]
Hey @daarxwalker Please try again with the new `v4` version of the library. We're now only transpiling ts into js, the rest is up to your bundler.
