### ISSUE TITLE
Remove prepublish minification

### ISSUE THREAD

**Issue by larrybotha** [sveltejs/svelte-preprocess#194]
**Is your feature request related to a problem? Please describe.**

Debugging transformations in a project when `svelte-preprocess`s source is minified is challenging.

**Describe the solution you'd like**

Remove minification step from `prePublishOnly` script

**How important is this feature to you?**

Minor. It's a minor inconvenience that `svelte-preprocess`s source is minified, as I'm not going to interact with it regularly.

**Additional context**

Is `svelte-preprocess` used in the browser anywhere? I'm unaware of any use-cases where it would be, but if it is, then I understand the need for minification, although minification is often left up to the user.

If it's not being used as a client-side library, then I'd recommend removing the minification, as there's little need for minifying Node modules, and it makes it straightforward for users to debug issues in their build configs.

**Comment by kaisermann** [comment]
Hey @larrybotha 👋  I totally feel your point and it makes complete sense. As `v4` is right around the corner, I'll be removing the minification step from there!

**Comment by larrybotha** [comment]
@kaisermann now that's great customer support \ :D /
