### ISSUE TITLE
SASS : Error : Undefined variable

### ISSUE THREAD

**Issue by Nokorbis** [sveltejs/svelte-preprocess#198]
**Describe the bug**
When using svelte-preprocess with node-sass, I can't build the project because sass cannot find my variables.scss file.
(That I specify in the prepend data)

**Logs**
```
PS F:\Dev\Envs\yeoman\test> npm run dev

> test@1.0.0 dev F:\Dev\Envs\yeoman\test
> rollup -c -w

rollup v2.21.0
bundles src/main.js → public\build\bundle.js...
[!] (plugin svelte) Error: Undefined variable: "$primary-color".
src\App.svelte
Error: Undefined variable: "$primary-color".
    at options.error (F:\Dev\Envs\yeoman\test\node_modules\node-sass\lib\index.js:291:26)
```
If I use "import" instead of "use" in preprendData :

```
> test@1.0.0 dev F:\Dev\Envs\yeoman\test
> rollup -c -w

rollup v2.21.0
bundles src/main.js → public\build\bundle.js...
[!] (plugin svelte) Error: File to import not found or unreadable: F:Þvnvsyeomantestsrc
ssetsstylesvariables.scss.
src\App.svelte
Error: File to import not found or unreadable: F:Þvnvsyeomantestsrc
ssetsstylesvariables.scss.
    at options.error (F:\Dev\Envs\yeoman\test\node_modules\node-sass\lib\index.js:291:26)
```

**To Reproduce**
I'm using windows.
I have tried running "npm run dev" in PowerShell and Command Prompt (same result)

https://github.com/Nokorbis/svelte-preprocess-sass-issue

**Expected behavior**
Using my variable in /src/assets/styles/variables.scss to build the App.svelte component

**Stacktraces**

**Information about your project:**

- Your browser and the version: 
Not going there

- Your operating system: 
 Windows 10

- `svelte-preprocess` version 
https://github.com/Nokorbis/svelte-preprocess-sass-issue/blob/master/package.json

- Whether your project uses Webpack or Rollup
Rollup

**Additional context**
Might be because this is not the C: drive ?
Honestly, I don't really think it comes from svelte-preprocess.
I think that might be because of the sass library.

When you look on the second log (whenI use "import" instead of "use"), it looks like it doesn't format properly my file path

**Comment by Nokorbis** [comment]
Might be linked to #192

**Comment by Nokorbis** [comment]
If I set the variable in the svelte file, the project compiles, but... well... not using my variables.scss file :D

**Comment by antony** [comment]
You need to import your variables file into components which use it, each component has an isolated scss scope, similarly to if you had multiple scss files.

**Comment by Nokorbis** [comment]
I'm not sure you read properly what I wrote ^^'

When I do an @import I have an error because of the path ^^'

**Comment by antony** [comment]
Apologies, this is a new feature I hadn't seen!

**Comment by Nokorbis** [comment]
Thank you !

**Comment by Nokorbis** [comment]
In the mean time, I edited the "App.svelte" file to add the import instruction and it works.
Thus, what needs to be figured out is why is the prepended data isn't formatted correctly. (It seems the \ characters is "removed" somehow ?)

**Comment by Nokorbis** [comment]
Well, I fixed it locally using a "replace" :
![image](https://user-images.githubusercontent.com/6314619/87231106-9d5f0080-c3b4-11ea-9df6-593f20b0ff0e.png)
I don't know if there is something you can do to avoid this kind of issue 🤔

**Comment by kaisermann** [comment]
Hey @Nokorbis 👋 

Thanks for debugging the issue! It seems scss only accepts posix-style paths. Switch that 

- `import path from 'path'` for `import { posix } from 'path'`
- `path.resolve` for `posix.resolve` 

And you should be good to go! I'll update the getting started section 😁
