### ISSUE TITLE
'Cannot find any of modules: sass,node-sass' when using NodeJS v1.14.5 (sapper)

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/svelte-preprocess#199]
**Describe the bug**
After installing NodeJS v1.14.5 i get the following error;

```
Cannot find any of modules: sass,node-sass
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'D:\project\__sapper__\dev\server\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Logs**
See above ^

**To Reproduce**
- Install the latest version of NodeJS or v1.14.5
- clone the sapper template (or your own)
- add svelte preprocess to your rollup config
- npm run dev/build.

**Expected behavior**
Not throw an error.

**Stacktraces**
See above  ^

**Information about your project:**

- Windows 10 (latest stable build)
- `svelte-preprocess` 
- Rollup

**Comment by Nokorbis** [comment]
Have you installed node-sass ?
It is specified that you need to install your preprocessors yourself
(using **npm i -D node-sass** in this case)

Probably to avoid installing so many preprocessors that you wouldn't even end up using

**Comment by UltraCakeBakery** [comment]
> Have you installed node-sass ?
> It is specified that you need to install your preprocessors yourself
> (using **npm i -D node-sass** in this case)
> 
> Probably to avoid installing so many preprocessors that you wouldn't even end up using

I have. Also did `npm update` to be sure after it didn't work the first time. No luck :/

**Comment by Nokorbis** [comment]
I tried to make a simple project, 
got the same error

**Comment by Nokorbis** [comment]
Oh my bad,
I forgot to add the preprocess call in the server side of the rollup config.

What about you @UltraCakeBakery  ?

However, my variables.scss files doesn't seem to be taken into account

**Comment by UltraCakeBakery** [comment]
@Nokorbis your error is a different one. Mine only started happing right after upgrading to NodeJS v1.14.5. Before that my setup worked fine. This is a svelte-preprocess compatibility issue

**Comment by kaisermann** [comment]
Hey @UltraCakeBakery 👋  Can you install the latest version and post the logged error? I've added the error details to the log.

**Comment by UltraCakeBakery** [comment]
Hey @kaisermann, is version 4.0.7 available on npm?
https://www.npmjs.com/package/svelte-preprocess

That is how I implemented svelte-preprocess in the first place. Wouldn't know how to do it otherwise 😅

**Comment by kaisermann** [comment]
Oops, forgot the `npm publish` 😅  It's on npm now!

**Comment by UltraCakeBakery** [comment]
@kaisermann 

```
Cannot find any of modules: sass,node-sass

Error: Missing binding D:\project\node_modules\node-sass\vendor\win32-x64-83\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 14.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 12.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'D:\project\__sapper__\dev\server\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Removing the node_modules folder in the root and ``src`` folder, and removing the package-lock.json solved it.
pretty sure the command suggested in the error would've worked too.

The issue is solved on my end. Thank you @kaisermann
