### ISSUE TITLE
Feature: type-checking

### ISSUE THREAD

**Issue by sharifzadesina** [sveltejs/svelte-preprocess#205]
Hi,
Unlike ts-loader, svelte-preprocess doesn't respect `noEmitOnError` compiler option, it seems right now we only report syntax errors and we ignore all other errors.
like if you do this:
```ts
let myvar: string = "hi";
myvar = [];
```
You will get no error.
But for normal Typescript files ts-loader, will report the error and will prevent files to be compiled.

**Comment by kaisermann** [comment]
`svelte-preprocess` doesn't do any kind of type-checking, it just transpiles your ts into js (see it [here](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#typescript---limitations)). If you want to fail your build when a type error is found, you can use [`svelte-check`](https://www.npmjs.com/package/svelte-check).

**Comment by sharifzadesina** [comment]
@kaisermann Why you just closed the issue?
Of course, I am aware of `svelte-check`, but it is not possible to use it alongside `preprocess`, you need to run it manually each time, or use a language-server and an editor that supports that language server.
but `ts-loader` does the type checking itself and prevents code from compiling.
I don't understand why you guys don't follow the standard behavior of typescript tools. what's the point of using typescript if I am going to type check in CLI?

**Comment by kaisermann** [comment]
@sharifzadesina From a user perspective, I understand your nuisance. However, type-checking all of a Svelte component's code is not as trivial as it is with React components or with simple TypeScript files.  We consciously decided to not type-check from `v4` onwards. Previously, we indeed did some sort of type-checking but it was not only very slow but also had a lot of false-positive errors. The current type-checking workflow would be type-checking in the IDE while developing via `svelte-vscode` and in a CI environment via `svelte-check`.

However, there have been a significative amount of folks asking why we don't throw an error if a type error is found. Following the rest of the optional features of this library,  maybe we can use the `svelte-language-server` via a `typeCheck: boolean` or even the `noEmitOnError: boolean` prop. The LSP would be an optional/peer dependency, of course.

**Comment by sharifzadesina** [comment]
@kaisermann bro I understand what you're saying, but while all standard TS tools do it, and they don't have any problem, why we shouldn't do it? some people use Notepad for developing, why we have to force them to use VSCode? or to run a CLI command each time? (I know they can use some kind of hook, but it is still a dirty solution).
and regardless of that, when someone wants type checking and secure code, he can forget about compilation speed.
Writing TypeScript without type checking is like writing Java code without type checking, imagine what it would be like.
I don't understand why you made that decision, At least you can keep `svelte-check` and maybe add it here also as an optional feature?

**Comment by dummdidumm** [comment]
Another approach would be to just add a watch-mode to `svelte-check`, which would be run in parallel to the normal dev compilation. Wouldn't this suffice? https://github.com/sveltejs/language-tools/issues/287

**Comment by dummdidumm** [comment]
If we do this inside `svelte-preprocess`, how would we make sure that

1. Diagnostics are run on all files, not just the ones which were changed?
2. Diagnostics are only invoked once?

**Comment by dummdidumm** [comment]
The more I think about it the more I feel like `svelte-preprocess` is not the right place to throw type check errors.

- [svelte-check](https://www.npmjs.com/package/svelte-check) now supports watch mode
- [This article](https://blog.scottlogic.com/2020/07/24/svelte-ts.html) shows how to integrate `svelte-check` with rollup. Maybe that's something to add to the official `rollup-plugin-svelte` (off by default)?

**Comment by sharifzadesina** [comment]
@dummdidumm Hi, I just check Nuxt.js (It is for Vue.js)
It also checks types and reports them to the user when you run the app.
We should do the same. or maybe just run svelte-check in watch mode along side svelte app.

**Comment by brunnerh** [comment]
TypeScript is all about finding errors at build time so i expect a TypeScript preprocessor to also throw these errors at build time.

**Comment by dummdidumm** [comment]
A preprocessor only gets the content of the `script` tag, which is only part of a svelte file. This will produce false errors. Think of this situation:

```
<script lang="ts">
    let a: number = 1;
</script>
{a}
```

`svelte-preprocess` only gets `let a: number = 1;` and the diagnostics would output that a is never used, which is wrong.

So there simply is no good way to make this part of the preprocessors.

To get TS errors at build time, just use `svelte-check` and run it as a pre-build-step.

**Comment by brunnerh** [comment]
Maybe this could be integrated as a kind of post-processing step then? Right now this breaks expectations and complicates things. I already have a webpack build on watch and ideally that would just show me the errors without the need to run another watcher in parallel.

**Comment by dummdidumm** [comment]
I agree that there are ways to make this easier / feel more built-in, but `svelte-preprocess` is the wrong place for this. A better place might be `svelte-loader` / `rollup-plugin-svelte`.

**Comment by kaisermann** [comment]
I'm on @dummdidumm's side here. Will close this in favor of issues in `svelte-loader` and `rollup-plugin-svelte`.
