### ISSUE TITLE
Babel with sourceMap crashes

### ISSUE THREAD

**Issue by Shvarpa** [sveltejs/svelte-preprocess#215]
**Describe the bug**
When using svelte preprocess with typescript & babel,  
if sourceMap option is enabled inside tsconfig.json,  webpack throws:  
<details>
      ERROR in ./src/index.svelte 
      Module build failed (from ./node_modules/svelte-loader/index.js): 
      Error: .inputSourceMap must be a boolean, object, or undefined
</details>
else, if soruceMap is disable everything works as intended.

**To Reproduce**
repo to reproduce the issue: https://github.com/Shvarpa/svelte-preprocess-babel-sourcemap-failure

**Expected behavior**
when using svelte-preprocess with babel to transpile typescript with webpack, webpack should serve the project without a problem

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace, @ is project root</summary>
ERROR in ./src/index.svelte
Module build failed (from ./node_modules/svelte-loader/index.js):
Error: .inputSourceMap must be a boolean, object, or undefined
    at assertInputSourceMap (@\node_modules\@babel\core\lib\config\validation\option-assertions.js:110:11)
    at @\node_modules\@babel\core\lib\config\validation\options.js:109:5
    at Array.forEach (<anonymous>)
    at validateNested (@\node_modules\@babel\core\lib\config\validation\options.js:85:21)
    at validate (@\node_modules\@babel\core\lib\config\validation\options.js:76:10)
    at loadPrivatePartialConfig (@\node_modules\@babel\core\lib\config\partial.js:76:50)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (@\node_modules\@babel\core\lib\config\full.js:57:46)
    at loadFullConfig.next (<anonymous>)
    at Object.transform (@\node_modules\@babel\core\lib\transform.js:25:45)
 @ ./src/index.ts 1:0-33 2:23-26
</details>

**Information about your project:**

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)
irrelevant 

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
Windows 10 v1909

- `svelte-preprocess` version (Please check you can reproduce the issue with the latest release!)
4.0.10

- Whether your project uses Webpack or Rollup
Webpacl

**Additional context**
problem seems to be caused because babel receives sourceMap as a json string instead of object at [`autoProcess.ts`](https://github.com/sveltejs/svelte-preprocess/blob/master/src/autoProcess.ts#L254-L286)

**Comment by kaisermann** [comment]
Hey, @Shvarpa 👋  Thanks for the repro! Fixed in `4.0.11`
