### ISSUE TITLE
PostCSS config not being loaded

### ISSUE THREAD

**Issue by saaduw** [sveltejs/svelte-preprocess#216]
**Describe the bug**
Working on a Electron project (using Svelte) + TailwindCSS with the help of PostCSS. (Used the guidelines here to get Tailwind working with Svelte: https://dev.to/sarioglu/using-svelte-with-tailwindcss-a-better-approach-47ph)

Everything was working perfectly until today when I could no longer build the electron app (`npm start`). The `postcss.config.js` file exists in the root of the project as does the svelte.config.js

The `postcss-load-config` is also correctly installed as a dev dependency.

The only conceivable change made to my dev environment in the past month has been updating my MacOS to 10.15.6

##### svelte.config.js
```
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
	preprocess: sveltePreprocess({
    scss: {
      data: `@import 'src/assets/styles/_base.scss';`
    },
    postcss: true
  }),  
};
```

##### postcss.config.js
```
const purgecss = require('@fullhuman/postcss-purgecss')({
  content: [
    './src/**/*.html',
    './src/**/*.svelte'
  ],

  whitelistPatterns: [/svelte-/],

  defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || []
});

const production = process.env.NODE_ENV === 'production'

module.exports = {
  plugins: [
    require('tailwindcss'),
    require('postcss-nested'),
    require('autoprefixer'),
    ...(production ? [purgecss] : [])
  ]
};
```

**Logs**
```
[svelte-preprocess] PostCSS configuration was not passed. If you expect to load it from a file, make sure to install "postcss-load-config" and try again ʕ•ᴥ•ʔ
```

**Expected behavior**
To be able to build my electron app with the styles correctly applied.

**Information about your project:**

- Your browser and the version: Electron 8.4.1

- Your operating system: MacOS 10.15.6

- Node version: 13.5.0

- `svelte-preprocess` version: 3.9.12

- Whether your project uses Webpack or Rollup: Neither. We use Parcel

**Comment by kaisermann** [comment]
Hey @saaduw 👋  `svelte-preprocess` was accidentally suppressing all kinds of errors and displaying that message. I've changed this behavior in `4.3.2` and, if the issue still exists, you should be able to see the correct error appearing.
