### ISSUE TITLE
[QUESTION] Alias

### ISSUE THREAD

**Issue by zamkevich** [sveltejs/svelte-preprocess#217]
Hey.
I am writing a PR and came across a code that greatly complicates the implementation, I don't understand why this is done, can you explain?

![image](https://user-images.githubusercontent.com/13717428/89863826-41271080-dbee-11ea-89e0-6fcec592a7aa.png)
![image](https://user-images.githubusercontent.com/13717428/89863879-5d2ab200-dbee-11ea-8938-93965832e944.png)

**Comment by kaisermann** [comment]
Hey @zamkevich 👋 

1) The alias map is used to translate file aliases to a certain language. `ts` to `typescript` etc. If you import a file via the `src=""` attribute, `svelte-preprocess` will try to use the file extension to infer its language. 

2) What hack? The `hasDepInstalled`? That whole block of code?

**Comment by zamkevich** [comment]
The last paragraph is what I needed to know, thanks! ❤️  
And is really hack 😅

**Comment by kaisermann** [comment]
@zamkevich I agree that we could change the way we skip any `postcss` content in the `getTransformerTo('css')`. Maybe a trivial check for the `lang === 'postcss'`. 

For the "running it after any style transformer" part, currently, I don't see another way to do it. I've been wanting to at least abstract those multiple `runTransformer` call into something more akin to a queue of transformers but didn't end up with a nice solution. 

What do you mean by "looks like a hack"? Any suggestion is welcome to at least be discussed!

**Comment by zamkevich** [comment]
I mean exactly what you said: change aliases for preventing double processing PostCSS, multiple runTransformer and then last run PostCSS processing — not a nice solution. It confuses a little bit 🤔  

But it's ok. I needed to understand the thing. Actually I totally forgot that a PostCSS is the last process run for styles 🤦‍♂️ 

Russians like to say "Hack" for solutions like this 🤷‍♂️
Sorry for this misunderstanding 😬
