### ISSUE TITLE
Left console.log in production

### ISSUE THREAD

**Issue by vadirn** [sveltejs/svelte-preprocess#218]
**Describe the bug**
`console.log` sneaked into release: https://github.com/sveltejs/svelte-preprocess/blob/c16e5b52679bd14418f2d242d572218fb6059c46/src/transformers/babel.ts#L24

**Logs**
NA

**To Reproduce**
NA

**Expected behavior**
`console.log` shouldn't be there 😅 

**Stacktraces**
NA

**Information about your project:**
NA

**Additional context**
NA

**Comment by kaisermann** [comment]
Hehe, oops! Thanks 🙏
