### ISSUE TITLE
Output processed svelte files

### ISSUE THREAD

**Issue by AhmedSayed77** [sveltejs/svelte-preprocess#219]
**Is your feature request related to a problem? Please describe.**
Importing a svelte component from package in a svelte app will import the original component from the source file, not the compiled one. That mean if I want to make component package using TS for example, everyone who uses must add the step of compiling TS to their build setup.

**Describe the solution you'd like**
Add the option to preprocess svelte files and ouput svelte files that contains vanilla JS, CSS and HTML.

**Describe alternatives you've considered**
Other than writing a rollup plugin in a separate repo, I doon't think there's any alternative.

**How important is this feature to you?**
If this feature is implemented it will make it easier to a build a package with good DX

**Additional context**
None

**Comment by kaisermann** [comment]
Hey, @AhmedSayed77 👋  That's a rollup/webpack/your bundler configuration ([rollup](https://github.com/sveltejs/rollup-plugin-svelte#pkgsvelte), [webpack](https://github.com/sveltejs/svelte-loader#resolvealias))! You could omit the `svelte` property of your package's `package.json` though.
