### ISSUE TITLE
Sass data not working with Sapper-Rollup

### ISSUE THREAD

**Issue by martonlederer** [sveltejs/svelte-preprocess#221]
I have a `_variables.sass` file that I want to import in every component. `svelte-preprocess` is not prepending the content of the `data` field, so Sapper throws the error `Undefined variable.`.
My rollup config: https://github.com/martonlederer/Sapper-starter-kit/blob/fdf9dbf57f9efaa7875e19d7cd3f39530a01ae05/rollup.config.js
Repo with commit point: https://github.com/martonlederer/Sapper-starter-kit/tree/fdf9dbf57f9efaa7875e19d7cd3f39530a01ae05

**Comment by kaisermann** [comment]
Hey @martonlederer 👋 

We've changed the `data` property to `prependData` in `v4`: https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#preprocessors. 

Also, if you're using the `autoPreprocess` method you don't need to import the separate processors:

```js
  svelteOptions = {
    dev: process.env.NODE_ENV !== 'development',
    hydratable: true,
    emitCss: true,
    preprocess: autoPreprocess({
      sass: { prependData: `@import '${ require('path').join(process.cwd(), 'src/styles/_variables.sass') }'` }),
      typescript:{ tsconfigFile }
    })
  }
```

**Comment by martonlederer** [comment]
Thank you very much

**Comment by freethebit** [comment]
> Hey @martonlederer wave
> 
> We've renamed the `data` property to `prependData` in `v4`: https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#preprocessors.
> 
> Also, if you're using the `autoPreprocess` method you don't need to import the separate processors:
> 
> ```js
>   svelteOptions = {
>     dev: process.env.NODE_ENV !== 'development',
>     hydratable: true,
>     emitCss: true,
>     preprocess: autoPreprocess({
>       sass: { prependData: `@import '${ require('path').join(process.cwd(), 'src/styles/_variables.sass') }'` }),
>       typescript:{ tsconfigFile }
>     })
>   }
> ```

just one thing missing `;` at the end of the string, replace:

```
'src/styles/_variables.sass') }'` }),
```

with:

```
'src/styles/_variables.sass') }';` }),
```

**Comment by martonlederer** [comment]
Don't think i need that. It's sass

**Comment by freethebit** [comment]
> Don't think i need that @freethebit. It's sass

Yes, my fault. It's only needed for scss.
