### ISSUE TITLE
wrong line number in style tags when there are empty lines above the issue

### ISSUE THREAD

**Issue by ivanhofer** [sveltejs/svelte-preprocess#229]
**Describe the bug**
Im using lang="scss" on my script tags. Whenever I have an empty line in my **nested** style definition before a lint-issue, it shows a wrong line number in the VS code Problems-panel. When I delete the empty lines, the line number is correct.

**To Reproduce**
Write styles and leave some blank lines.

In this example the "a.active" style tag is not in my html-template. But the line number points to the line containing "padding".
![image](https://user-images.githubusercontent.com/21335119/91273951-4c497700-e77e-11ea-83ac-00ab5c7dd578.png)

PS: I'm using an extension that inlines linting issues from the problems-panel directly into the file.

**Expected behavior**
The line number should be correct also when I have empty lines in my style definitions.

**Information about your project:**

- Your operating system: Windows 10
- `svelte-preprocess` version: 4.1.1
- Rollup
- I'm using the official Svelte Extension for VSCode.

**Comment by jasonlyu123** [comment]
You probably need to enable source map in non-production environment or at least in the `svelte.config.js`

**Comment by kaisermann** [comment]
Gotta test why that's happening, but we can try defaulting it to `process.env.NODE_ENV === 'development'`.

**Comment by ivanhofer** [comment]
@jasonlyu123 thanks, with setting the `sourceMap` option inside the preprocessing function in my `svelte.config.ts,` it's working now.
I found another small issue. When I have the following selector,
```
a {
   ...

   &.some-class,
   &.another-class,
   &.unused-class {
      ...
   }
}
```
the unused selector warning will appear at the first line `&.some-class` and not at the third line `&.unused-class`.
If this could be fixed easily, it would be great. But it's not a big issue (for me at least).

Thanks for your awesome work!
