### ISSUE TITLE
sourceMap is not true by default

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/svelte-preprocess#230]
**Describe the bug**
[According to the documentation](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#auto-preprocessing-options), `sourceMap` is `true` by default, but if I'm interpreting [the code](https://github.com/sveltejs/svelte-preprocess/blob/master/src/autoProcess.ts#L103) correctly, it's set to `false` by default.

**To Reproduce**
Use autopreprocess mode without any options, have this file

```html
<script lang="ts">
  interface A {}
  export let a;
</script>
```

Warning is in the `interface` line, not in the `export` line.

**Expected behavior**
Align docs and code.

**Information about your project:**

- Your browser and the version: -
- Your operating system: Windows
- `svelte-preprocess` version 4.1.1
- Rollup

**Comment by kaisermann** [comment]
Hey 👋  The doc is indeed wrong 😅. Fixed!
