### ISSUE TITLE
"Cannot read property 'split' of null" issue with svelte-preprocess and scss

### ISSUE THREAD

**Issue by riccardolardi** [sveltejs/svelte-preprocess#241]
The same works in pure Svelte but does throw an error in Sapper:

An imported scss file in _layout.svelte:

```
<style type="text/scss">
  @import "../style/style.scss";
</style>
```

```
.my-div {
  &.my-class {
    color: blue; // this throws error
    another-div {
      color: blue; // this doesn't
    }
  }
}
```

It seems that when using the scss ampersand, directly setting css throws this error `Cannot read property 'split' of null`. The same works fine in pure Svelte. See the repo https://github.com/riccardolardi/sapper-scss to reproduce. The line causing the error is in `src/style/_nav.scss` on line 12.

Redirected from here: https://github.com/sveltejs/sapper/issues/1496

Any hint on this?

**Comment by benmccann** [comment]
Here's the full stack trace from https://github.com/sveltejs/sapper/issues/1496:

```
➜ npm run build

> TODO@0.0.1 build /Users/riccardolardi/Code/sapper-scss
> sapper build --legacy

> Building...

[!] (plugin svelte) TypeError: Cannot read property 'split' of null
/Users/riccardolardi/Code/sapper-scss/src/components/Nav.svelte
TypeError: Cannot read property 'split' of null
    at test_attribute (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23486:34)
    at attribute_matches (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23584:14)
    at block_might_apply_to_node (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23458:19)
    at apply_selector (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23400:14)
    at Selector$1.apply (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23297:10)
    at /Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23668:54
    at Array.forEach (<anonymous>)
    at Rule$1.apply (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23668:25)
    at Stylesheet.apply (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23939:20)
    at new Element$1 (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:24709:31)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TODO@0.0.1 build: `sapper build --legacy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TODO@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/riccardolardi/.npm/_logs/2020-09-08T16_51_41_784Z-debug.log
```

**Comment by kaisermann** [comment]
Hey @riccardolardi 👋 

Thanks for the repro! I'm not sure exactly what's happening here. I've managed to isolate the error to the `nav.scss` file. The simplified generated code is:

```css
nav ul.nav-items {
  margin-bottom: 4.8vmax;
}
nav ul.nav-items li {
  margin-right: 1.2vmax;
}
nav ul.nav-items li:last-child {
  margin-right: 0;
}
/*# sourceMappingURL=src/components/Nav.svelte.map */
```

The problematic declaration is the `nav ul.nav-items`.

If you remove `svelte-preprocess` from your config and paste that CSS directly in the `Nav.svelte`, the problem seems to persist.

**Comment by kaisermann** [comment]
Oh, it's definitely not related to `svelte-preprocess`. It has something to do with those `class` ternaries that can result in `null`. If you change them to `''` (empty string) the error seems to disappear.

**Comment by riccardolardi** [comment]
Thanks a lot @kaisermann !

How did you see them result in null? They are an important part of SCSS and haven't failed me in ages otherwise, be it in react or wherever.
