### ISSUE TITLE
[Syntax] Error: Undefined Variable

### ISSUE THREAD

**Issue by oyeyipowale** [sveltejs/svelte-preprocess#244]
**Describe the bug**
Using `prependData` (following the doc) for scss setup, sass variable defined, although works fine, shows a error squiggly line.

**Logs**
none

**Additional context**
I actually got the red line to go away with a direct `@import` of `variable.scss` to into the component (this is a sapper project).
![image](https://user-images.githubusercontent.com/16971163/92957410-65ca0e80-f460-11ea-92c8-60deb6e9888d.png)
I was wondering if there is a better way to get around this issue instead of import the `variable.scss` file where ever it's content is being used.

**Comment by kaisermann** [comment]
Hey @oyeyipowale 👋  Do you have a `svelte.config.js` file in your project's root?

**Comment by oyeyipowale** [comment]
Thanks. No, I do not at the moment. Could it help resolve the issue? @kaisermann

**Comment by oyeyipowale** [comment]
Hey @kaisermann , followed your suggestion and did setup the `svelte.config.js` file which made the issue resolved. Thanks again!
