### ISSUE TITLE
Indent should be stripped for lang=postcss to allow for use with sugarss parser

### ISSUE THREAD

**Issue by danielnarey** [sveltejs/svelte-preprocess#250]
The bug fix in [v4.0.10](https://github.com/sveltejs/svelte-preprocess/commit/8d735bde959709fc204de12cc5543194a29e28a0) broke my build. The SugarSS parser is indentation sensitive. When used with svelte-preprocess in a `<style lang="postcss" >` block,  the indent is not stripped out and the parser throws an error. I rolled back to v4.0.9 and the build succeeded.

**Comment by kaisermann** [comment]
Hey, @danielnarey 👋  Sorry for the regression. I'll add the proper config when possible, but for now you can pass `stripIndent` in your `postcss` config and you should be good to go!

**Comment by kaisermann** [comment]
A quick thought about this one: we can't blindly strip indentation for any kind of PostCSS code as it could result in errors with wrong column numbers, which is already a problem. We could look if the config has a `parser` property, but I don't know if that would be sufficient for most cases. What parsers are available for postcss?

**Comment by danielnarey** [comment]
I don’t know how many parsers are out there for PostCSS. There appear to be at least a few others. One idea would be to allow `<style lang="sugarss">`, which would mean: strip any extra indentation, then process the style block with PostCSS.

**Comment by kaisermann** [comment]
@danielnarey Oh, I like `lang="sugarss"`! It's analagous to `sass` for `scss` and we already have every piece of the puzzle ready. Will try to tackle this soon!
