### ISSUE TITLE
No (separate) source maps for PostCSS

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/svelte-preprocess#251]
**Describe the bug**
When preprocessing PostCSS, there is no source map returned although PostCSS supports it.

**To Reproduce**
Preprocess any file with postcss and see that `map` of the returned object is undefined.

**Expected behavior**
A `map` object is returned.

**Reason / how to fix this**
PostCSS's [SourceMap options](https://postcss.org/api/#sourcemapoptions) have an option `inline` which is `true` by default. The result is that the source maps are inlined in the output and not returned in the `map` object. Setting this to `false` will fix this. I suggest to make `inline: false` the default but also allow to override these options. [Currently this is not possible](https://github.com/sveltejs/svelte-preprocess/blob/master/src/transformers/postcss.ts#L14).

**Information about your project:**

- Your browser and the version: -

- Your operating system: Windows

- `svelte-preprocess` version (Please check you can reproduce the issue with the latest release!): Latest

- Whether your project uses Webpack or Rollup: Rollup

**Additional context**

Would be great to have this so we can process the information in language-tools and show Svelte warnings at the correct positions.

**Comment by HelenDias** [comment]
Hi @kaisermann! Can you assignee me to this bug?
I would like to help 😄
