### ISSUE TITLE
Do preprocess without bundling

### ISSUE THREAD

**Issue by pd4d10** [sveltejs/svelte-preprocess#255]
**Is your feature request related to a problem? Please describe.**

When using svelte to develop a library, it is recommended to ship source code (*.svelte) to npm and add a `svelte` field to `package.json`([from this document](https://github.com/sveltejs/rollup-plugin-svelte#pkgsvelte)). If this library is used by someone, the rollup plugin would take these source code and recompile them.

The problem is, if some preprocessors are used in the library development (for example TypeScript), all users of this lib have to add these preprocessors to their app/library project, because rollup plugin would take the source code and recompile them.

**Describe the solution you'd like**

Provide a way to do preprocess without bundling. Take TypeScript as an example, input is `<script lang="ts">/* TS code */</script>` and output is `<script>/* JS code */</script>`

**How important is this feature to you?**

We encountered this problem when developing [ByteMD](https://github.com/bytedance/bytemd), which is a hackable Markdown editor built with Svelte.

**Comment by kaisermann** [comment]
Hey, @pd4d10 👋  This feature is unrelated to `svelte-preprocess` since you can achieve what you want by calling`svelte-preprocess` in some node script. However, if more people show an interest in an easy way to just preprocess their components to some directory, we can create a simple CLI for that.

**Comment by pd4d10** [comment]
OK, I will do some digging and send a PR if possible
