### ISSUE TITLE
postcss v8 incompatibility: error TS2503: Cannot find namespace 'postcss'

### ISSUE THREAD

**Issue by btakita** [sveltejs/svelte-preprocess#258]
As of 4.3.2:

```
error TS2503: Cannot find namespace 'postcss'

plugins?: postcss.AcceptedPlugin[];
```

It looks like there's a peer dependency

```
"postcss": "^7.0.32",
```

Need to include v8 in the peer dependency check.

**Comment by lukeed** [comment]
I think this can be any of: 

* `"postcss": "^7.0.32 || ^8",
* `"postcss": ">7.0.32",`
* `"postcss": "*",`

I don't think everyone will be ready to upgrade to 8.0, even though the migration process is minor. Would also have to check if the postcss config loader package changed.

**Comment by btakita** [comment]
I added `pnpmfile.js` to force postcss: ^8.0.9 & still get the error.

```js
module.exports = {
  hooks: {
    readPackage (pkg) {
      switch (pkg.name) {
        case 'svelte-preprocess':
          pkg.peerDependencies['postcss'] = '^8.0.9'
          break
      }
      return pkg
    }
  }
}
```

```
error TS2503: Cannot find namespace 'postcss'

plugins?: postcss.AcceptedPlugin[];
```

It appears I made an assumption. There is a different issue w/ pnpm, typescript, & svelte-preprocess

**Comment by kaisermann** [comment]
Hey, 👋 the way `postcss` exported its types changed. Using `import type * as postcss from 'postcss'` seems to work in both 7 and 8 in my local tests.
