### ISSUE TITLE
VS code setup documentation improvement

### ISSUE THREAD

**Issue by oyeyipowale** [sveltejs/svelte-preprocess#268]
**Is your feature request related to a problem? Please describe.**
The setup for svelte-process for vs code is quite great. However, a simple missing step got me confused till I find the solution after searching the interweb. This step i believe should be mention in [the usage.md -> With Svelte VS Code doc. ](https://github.com/sveltejs/svelte-preprocess/blob/master/docs/usage.md#with-svelte-vs-code) is the addition of node path to the svelte language server runtime.

**Describe the solution you'd like**
If one had not setup the **language server runtime** node path for svelte, the syntax error swiggly red line still shows up even after including `svelte.config.js` as required.

**Additional context**
The missing step is to goto the  VS Code preference >> settings >> search for "Svelte > Language-server: Runtime", then add your node path. This might be optional, but will save unnecessary confusion and headaches down the road.

**Comment by dummdidumm** [comment]
That should net be needed in most cases. My guess is you use sass/scss with `node-sass`? In that case it's actually needed.

**Comment by kaisermann** [comment]
I've never had the need to add any kind of extra configuration to svelte's language tools. As @dummdidumm said, this should not be needed in most cases. If you are able to explain and summarize what happened in your case, we can add a section to the vscode usage section.

**Comment by AlexGalays** [comment]
Well, it's still very annoying to fix when we DO happen to use `node-sass` as the error points to the wrong direction.

Or did you mean that `sass` should always be prefered over`node-sass`?

node version: v14.14.0
node-sass version: 4.14.1

Error =>

![image](https://user-images.githubusercontent.com/1375586/97034743-a93a9100-1565-11eb-81e3-7274670b150c.png)

If I set the path to the local language server which is the one that is used in the first place, the error goes away.

**Comment by dummdidumm** [comment]
The error message is pretty descriptive, the third paragraph gives the exact suggestion to solve this. So I'm not sure that this needs to be documented, given that `node-sass` is deprecated now.

**Comment by dummdidumm** [comment]
Closing as I think the error message is descriptive enough. Since `node-sass` is deprecated, this will become an edge case more and more over time.

**Comment by AlexGalays** [comment]
(agreed!)
