### ISSUE TITLE
global styling is not working anymore

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/svelte-preprocess#272]
**Describe the bug**
In the docs it says that we can wrap multiple elements inside` :global` like so:

```
<style lang="scss">
:global {
     html {}
     body {}
}
</style>
```

This now throws an error.

![image](https://user-images.githubusercontent.com/12383587/96869952-7cf11880-1470-11eb-852b-054d69a661bf.png)

Adding the `global` flag/prop to a `<style>` tag like so: `<style lang="scss" global>` and removing the `:global` wrapper doesn't work either. It adds the styles, but it isn't added globally. Just scoped to the component itself.
![image](https://user-images.githubusercontent.com/12383587/96871161-2b498d80-1472-11eb-9801-25485d2dc118.png)
console:
![image](https://user-images.githubusercontent.com/12383587/96871232-47e5c580-1472-11eb-8921-f93efbdb8e29.png)

**Logs**
```
P:\my-sapper-thinggy\src\routes\_layout.svelte
:global() must contain a selector
16: </main>
17:
18: <style lang="scss">:global html, :global body {
                       ^
19:   margin: 0px;
20:   height: 100%;
✗ server
P:\my-sapper-thinggy\src\routes\_layout.svelte
:global() must contain a selector
16: </main>
17:
18: <style lang="scss">:global html, :global body {
                       ^
19:   margin: 0px;
20:   height: 100%;
internal/modules/cjs/loader.js:1033
  throw err;
```

**To Reproduce**
1. Get the default sapper rollup template
2. Add svelte preprocess to your svelte config and rollup config
3. Paste my snippet above in to your _layout `<style lang="scss>` tag

**Expected behavior**
Not do this.

**Information about your project:**
```
        "node-sass": "^4.14.1",
        "sapper": "0.28.9",
        "svelte": "3.25.0",
        "svelte-preprocess": "^4.5.1"
```

**Additional context**

**Comment by kaisermann** [comment]
Hey @UltraCakeBakery  👋 

Do you have `postcss` installed? `svelte-preprocess` needs it to globalify your component's css..

**Comment by UltraCakeBakery** [comment]
ugh, this is the second time I forget to install postcss 🙈! My bad!

**Comment by kaisermann** [comment]
@UltraCakeBakery heh 😁  Just came to my mind that we could at least warn if someone uses the `global` attribute without having `postcss` installed.
