### ISSUE TITLE
Reccomend svelte.config.js

### ISSUE THREAD

**Issue by firefish5000** [sveltejs/svelte-preprocess#274]
Currently the docs only mention `svelte.config.js` as an integration step for VS-Code. 
It is not even mentioned in the readme, despite the fact it contains enough core to set up the build step for those already familure with the preprocessors they wish to use (everybody who wants to use a preprocessor, excluding first timers to a given language).
This makes it super easy for new users to miss the docs and is a semi-frequent cause of confused users in discord.

**Describe the solution you'd like**
I believe it would be a prudent to *always* suggest it as the place to configure things.
It is recommended by language-tools, necessary for the only officially supported editor/plugin,
and is currently the best-practice for easy integration/switching of build tools (snowpack even reads it on its own).
If/when we finally get an official preprocessor cli, the file will also be wanted/required by it.

The svelte ecosystem revolves around this file already, so treating it as *the standard*
instead of an extra step seems like the way to go.
For conditional configuration, the `createPreprocessors` function suggested by language tools could be reused.
If you want to ensure users know that the file isn't required, a small note that you can also do this directly in rollup/webpack/snowpack could be added in small letters at the bottom of some deeply hidden doc page.

**Describe alternatives you've considered**
* Directly link the related language-tools docs.
* Leave it as is and hope users eventually figure it out on their own.

**How important is this feature?**
Moderate. This affects most people trying to use preprocessors and there are probably several who followed the readme, got build working, and simply live with the broken ide/editor experience believing its NYI.

**Comment by antony** [comment]
I've opened https://github.com/sveltejs/svelte-preprocess/pull/366
