### ISSUE TITLE
Please add an import resolver for tilde (~) node_modules imports

### ISSUE THREAD

**Issue by GitGangGuy** [sveltejs/svelte-preprocess#277]
I know that svelte-preprocess adds `node_modules` to the scss/sass `includePaths` automatically, but this will only resolve import/use statements in the form of `module/...`, not `~module/...`, which has become a standard for importing modules in scss. Even VSCode will highlight and link paths relative to `node_modules` when prefixing them with a tilde (a path without one will however not be resolved correctly).
Would it be possible to treat tilde-prefixed paths as relative to `node_modules` as well, like a lot of webpack plugins have been doing already?

**Comment by kaisermann** [comment]
Hey @GitGangGuy 👋 

I think it's possible to add a custom `importer` that just removes the initial `~` character and leave the rest to the `includePaths` resolution. Will come back to you.

**Comment by GitGangGuy** [comment]
@kaisermann Thank you for addressing this!

**Comment by kaisermann** [comment]
It seems sass doesn't pass an importer returned value through the `includePaths` and it expects an absolute path. This complicates it a little bit more. For now, you could try using [`node-sass-tilde-importer`](https://github.com/matthewdavidson/node-sass-tilde-importer) and see if it works for you!

**Comment by GitGangGuy** [comment]
@kaisermann I use dart `sass`, so `node-sass` extensions aren't an option. Thanks for getting it working anyway!

**Comment by kaisermann** [comment]
@GitGangGuy AFIK both `sass` and `node-sass` importers have the same API. It's just a function.

**Comment by GitGangGuy** [comment]
The PR was merged, why is this issue still open? ^^
I'll go ahead and close it
