### ISSUE TITLE
Autocompletion of imported variables from external SCSS Files.

### ISSUE THREAD

**Issue by MarkTanashchuk** [sveltejs/svelte-preprocess#279]
I really miss auto-completion of variables and other things I import from separate `.scss` files.

In standard (`.scss`) files it works, for example, there are extensions like `SCSS IntelliSense`, and it would be nice if in style tag in components with `lang="s(a/c)ss"` it could be possible to also have auto-completion from files located either in a certain directory or in workspace.

**Comment by kaisermann** [comment]
This is unrelated to `svelte-preprocess`. I'm not sure if it's something doable, but https://github.com/sveltejs/language-tools/ could be a better place for it.
