### ISSUE TITLE
scss cannot import 

### ISSUE THREAD

**Issue by MS-ELEX** [sveltejs/svelte-preprocess#296]
I 've tried to import "scss".
App.svelte
<script>
import "./App.scss";
</script>

`
ParseError: \src\App.scss
SyntaxError: Unexpected character '@' (4:0)
    @import "@material/theme/mdc-theme";
`    
but style tag
 <style src="./App.scss" global></style> 
 

Works correctly！！

 why????

**Comment by MS-ELEX** [comment]
rollup.config.js
      
        svelte({
            dev: !production, // run-time checks      
            // Extract component CSS — better performance
            hot: isNollup,
            css: css => css.write(`bundle.css`),
            preprocess: [
                autoPreprocess({
                    sourceMap: !production,
                        defaults: {
                            //   markup: 'pug',
                            //   script: 'typescript',
                            //  style: 'scss'
                            },
                        scss: {
                            //prependData: `@import 'src/theme/smui-theme'`,
                            includePaths: [
                                './src/theme',
                                './node_modules',

                                //path.resolve(__dirname, '..', 'node_modules')
                            ]
                        },
                        postcss: { 
                            plugins: [require('autoprefixer')()],
                            //plugins: [postcssImport()] 
                        },
                    defaults: { style: 'postcss' }

**Comment by kaisermann** [comment]
Hey @MS-ELEX 👋  Please don't remove the issue template 🙏 

You can't import `scss` files inside your script tag with just `svelte-preprocess`. We only support SCSS inside the style tag.
