### ISSUE TITLE
Can't find postcss config file

### ISSUE THREAD

**Issue by RedHatter** [sveltejs/svelte-preprocess#298]
[Example repo](https://github.com/RedHatter/svelte-preprocess-bug)

I can't get svelte-preprocess to find a PostCSS config file.

With just
```
sveltePreprocess()
```
PostCSS is not processed at all. With
```
sveltePreprocess({
  postcss: {}
})
```
PostCSS is ran but I get the erorr message
```
[svelte-preprocess] PostCSS configuration was not passed. If you expect to load it from a file make sure to install "postcss-load-config" and try again.
```
Even though `postcss-load-config` is installed. With
```
sveltePreprocess({
  postcss: {
    plugins: [ ... ]
  }
}),
```
everything works as expected but I would like to define an external PostCSS config file.

**Comment by kaisermann** [comment]
Hey @RedHatter, set it to `true` and you should be good to go! See it here in the docs: https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#postcss-sugarss

**Comment by RedHatter** [comment]
Thank you for the quick reply @kaisermann.

I tired you solution but it doesn't seem to work. I still get
```
PostCSS configuration was not passed. If you expect to load it from a file make sure to install "postcss-load-config" and try again.
```
See updated repo.

**Comment by kaisermann** [comment]
I think you're missing a `.` dot at the beginning of the filename. `postcssrc.json` should be `.postcssrc.json`
