### ISSUE TITLE
Support "extends" tsconfig directive

### ISSUE THREAD

**Issue by raythurnevoid** [sveltejs/svelte-preprocess#300]
**Is your feature request related to a problem? Please describe.**
svelte-preprocess seems to not follows the extends directive provided in a tsconfig.

**Describe the solution you'd like**
Using `typescript.parseJsonConfigFileContent` should do the trick.

**How important is this feature to you?**
It's not blocking, since i could implement my custom tsconfig file reader, but it would be nice to have this feature built-in.

**Comment by kaisermann** [comment]
Hey @raythurnevoid 👋 

If I'm not mistaken, the `parseJsonConfigFileContent` needs a valid `ParseConfigHost`, which is a bit too much for this IMO. Can you check if #302 would be enough?

**Comment by raythurnevoid** [comment]
Thank you for the reply!
Unfortunately it's not enough :(.
There are two main issues, **it's not recursive** and `require` **will break with comments in tsconfig.json** (which "@tsconfig/svelte/tsconfig.json" has).

Actually [also ts-loader takes advantage](https://github.com/TypeStrong/ts-loader/blob/cafc933deccd2ea816d41a8de0289d8a8ce36348/src/config.ts#L132) of `parseJsonConfigFileContent`; it woud allow you to avoid much custom code with the confidence of it working in all occasions.
I know you need `ParseConfigHost` but you can easily overcome this by passing the sys object exposed under "typescript" package as achieved by ts-loader.

Don't know if it is of any help, i show you [what i came up so far](https://github.com/raythurnevoid/svelte-template/blob/main/build/utils/readTsConfig.ts). It doesn't use `parseJsonConfigFileContent` since i have to pass a compilerOptions object in the same format of a regular tsconfig.json, and `parseJsonConfigFileContent` unfortunately doesn't provide it. The problem of my implementation is that it doesn't work with globally installed node_modules and neither with node_modules present in parent folders of the cwd.

**Comment by kaisermann** [comment]
@raythurnevoid Thanks for the reference links! I will take a look at them and see what I come up with.
