### ISSUE TITLE
Using global on style tag errors with "'global' attribute found, but 'postcss' is not installed."

### ISSUE THREAD

**Issue by benmccann** [sveltejs/svelte-preprocess#301]
**Describe the bug**

Using `global` as follows does not work:
```
<style lang="scss" global>
```

**Logs**
SvelteKit prints:
```
[svelte-preprocess] 'global' attribute found, but 'postcss' is not installed.
```

It's weird that it's wanting postcss since I'm trying to use scss

**To Reproduce**
I've checked in the code here: https://github.com/benmccann/c3

**Information about your project:**

- Your operating system: Ubuntu

- `svelte-preprocess` version: 4.6.3

- Whether your project uses Webpack or Rollup: SvelteKit. i.e. Snowpack & Rollup

**Additional context**
I'm fairly new to using `svelte-preprocess` and might be doing something dumb

**Comment by kaisermann** [comment]
Hey @benmccann 👋 

This happens because we use `postcss` to walk through the (preprocessed) CSS and modify the selectors (there's a tiny note in the README stating that you need it installed). However, this message could be definitely improved 😅

**Comment by benmccann** [comment]
Oh, thanks! That really helps. I appreciate the explanation
