### ISSUE TITLE
Cannot use inline arrow functions in pug

### ISSUE THREAD

**Issue by Chamartin3** [sveltejs/svelte-preprocess#303]
Im trying to invoke a arrow function inside an an element, it is useful when you do not want to declare a one off function for a simple task and when you just want to invoke another function calling passing a specific argument that could be a result of an iteration. My code loos like this:
```

 const globalAtributes = {};
<script/>

<template lang="pug">
  +each('items as item')
    .field.is-horizontal(on:click='{()=>(onEnter(item, globalAtributes))}' )
      .field-body

```
When i check the error I can see that the issue is that the arrow function is transformed to another character:
```
{#each items as item}
  <div class="field is-horizontal" on:click="{()=&gt;(onEnter(item, globalAtributes))}">
<div class="field-body"
```
Not sure if i can change something to make it work, of if the problem is in the pug compiler. or hoy to turn the "&gt;" into "=>"

Im using
-  Ubuntu 20.04.1LTS
-  "svelte-preprocess": "^4.6.3"
-   "pug": "^3.0.0",
-   Rollup

**Comment by kaisermann** [comment]
Hey @Chamartin3 👋 

See https://github.com/sveltejs/svelte-preprocess/issues/271#issuecomment-714436260

**Comment by Chamartin3** [comment]
Oh.. sorry I did not say that other comment! i was trying to use the encoding scape  like this  !{}. I cannot believe that I did not read that part of the documentation. Thanks \u{1F605}
