### ISSUE TITLE
Errors upon encountering schema.org markup

### ISSUE THREAD

**Issue by benmccann** [sveltejs/svelte-preprocess#305]
**Describe the bug**

Google recommends using schema.org JSON-LD markup so that they can better understand your website, but `svelte-preprocess` barfs upon encountering it

**Logs**

The error was encountered at:
```
node_modules/svelte-preprocess/dist/autoProcess.js:36:77
```

https://github.com/sveltejs/svelte-preprocess/blob/5fe9a4382de4bd34a43d99b97ee802e2cf2910ca/src/autoProcess.ts#L72

**To Reproduce**

Paste the example `<script type="application/ld+json">` from https://developers.google.com/search/docs/guides/intro-structured-data into an app

**Expected behavior**

`svelte-preprocess` should proceed silently when encountering an unrecognized script type

**Stack**

```
Build Error: @snowpack/plugin-svelte
Error: Cannot find module './transformers/ld+json'
Require stack:
- node_modules/svelte-preprocess/dist/autoProcess.js
- c3-next/node_modules/svelte-preprocess/dist/index.js
- c3-next/svelte.config.js
- c3-next/@root
```

**Comment by benmccann** [comment]
I found it can be worked around with the `preserve` option: https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#auto-preprocessing-options

**Comment by kaisermann** [comment]
Hmmmm, should the `preserve` property have default values such as `ld+json`?

**Comment by benmccann** [comment]
I think I'd probably just ignore unrecognized language types instead since it'd probably be hard to come up with a complete list of ones to whitelist

**Comment by kaisermann** [comment]
@benmccann That makes total sense 😅 will do it soon.

**Comment by Antoine-lb** [comment]
> I found it can be worked around with the `preserve` option: https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#auto-preprocessing-options

@benmccann 's answer is good (e.g. it compiles), but is probably not enough if you are trying to make a schema dynamically. 

I found an article that really nailed the job for me so I just wanted to share: 
https://navillus.dev/blog/json-ld-in-sveltekit
