### ISSUE TITLE
Strange behavior with postcss and custom languages

### ISSUE THREAD

**Issue by non25** [sveltejs/svelte-preprocess#309]
I've been messing around with `svelte-preprocess`, trying to squeeze more performance for `tailwindcss` and got some interesting results instead...

For example I can make custom langs, to make purpose-fit performant configs for certain tasks.

```javascript
preprocess: sveltePreprocess({
  custom({ content, filename }) {
    return postcss(customPlugins)
      .process(content, { from: filename })
      .then(({ css: code, map }) => ({ code, map }))
      .then(({ code, map }) => {
        console.log('custom launched');
        return { code, map };
      });
  }
})
```

And every time component with `lang="custom"` is being built, I get two console logs, indicating that postcss has run twice instead of once. :thinking: 

Also I can configure postcss for `lang="postcss"` how I see fit just for `svelte-preprocess`, and make some default configuration for regular style tags while I'm at it:

```javascript
preprocess: sveltePreprocess({

  defaults: { style: 'style' },
  style({ content, filename }) {
    return postcss([postcssImport])
      .process(content, { from: filename })
      .then(({ css: code, map }) => ({ code, map }))
      .then(({ code, map }) => {
        console.log('style launched');
        return { code, map };
      });
  },

  postcss({ content, filename }) {
    return postcss(otherPlugins)
      .process(content, { from: filename })
      .then(({ css: code, map }) => ({ code, map }))
      .then(({ code, map }) => {
        console.log('postcss launched');
        return { code, map };
      });
  },
  // or
  postcss: {
    plugins: postcssConfig.plugins
  }

})
```

And I will get both of them run for regular style tags.
So if I use `postcss: true` or `postcss() {...}` function - it will launch it for regular style tags along with what I have defined as default.
The only way to prevent this from happening is to avoid using truthy `postcss` key in config.

I don't think `svelte-preprocess` should work like this. It is unintuitive at best. :thinking:

**Comment by kaisermann** [comment]
Hey @non25 👋 this happens because we purposefully run postcss **after** a possible style preprocessor, so it's possible to have postcss being executed after a scss style was reprocessed. It's the same for the babel preprocessor. It always runs after a script tag was preprocessed.

**Comment by non25** [comment]
Hi @kaisermann :slightly_smiling_face: Thanks for a fast response.

What do you think about having an option which controls such behavior ?

And more important, what about double run for custom languages ? Is that intentional too ? :thinking:

**Comment by kaisermann** [comment]
@non25 Can you provide a minimal repro with that happening?

And, in theory, the mechanism to disable such postcss behavior would be `postcss: not-truthy`. I'm not sure what we could do to change the current behavior apart from that, but I'm open to listening to ideas.

**Comment by non25** [comment]
@kaisermann Sure, take a look.

https://github.com/non25/svelte-template-webpack/commits/svelte-preprocess-repro

**Comment by kaisermann** [comment]
Oh, interesting! There's indeed an issue here. We're getting double `custom` logs because the `custom` transformer is taking precedence over the postcss one. Will try fix that soon!

**Comment by non25** [comment]
Cool. :slightly_smiling_face: 
What about conditionally skipping subsequent postcss run depending on something like `skipPostcss: true` present in previous processor's returned object ? :thinking: 
I think that would be nice addition.

**Comment by kaisermann** [comment]
IMO, having something like `skipPostcss` seems too specific and edge-casey. If you don't want two `postcss` implementations overlapping, you could can create two custom transformers `custom1` and `custom2` and call whatever you want in them.  That would also "fix" (for you) the double log issue.

**Comment by non25** [comment]
Is there a good-looking way to wrap default `scss/sass` processor to be able to extend it's functionality? :thinking:
I saw exports in `index.js`.
Reimplementing scss/sass processor in the config is kinda messy.
I'll try to experiment later...
Thanks. :slightly_smiling_face:

**Comment by kaisermann** [comment]
@non25 That option exists as a way to override the lib's native transformers, not extend them. I wouldn't say your way is ugly considering what you want to do.
