### ISSUE TITLE
[auto preprocess] Don't try to preprocess unknown language

### ISSUE THREAD

**Issue by kaisermann** [sveltejs/svelte-preprocess#312]
_Originally posted by @kaisermann in https://github.com/sveltejs/svelte-preprocess/issues/305#issuecomment-772765516_

In auto preprocess mode, we currently error out if the lib encounters an unknown language/transformer. We could just skip instead and let another preprocessor handle it. This seems to be another reason to rewrite the auto preprocess module (as mentioned in #311).

**Comment by benmccann** [comment]
Addressing this would also simplify partytown setup: https://partytown.builder.io/sveltekit#4-optional-svelte-preprocess-configuration
