### ISSUE TITLE
Add built-in support for windicss

### ISSUE THREAD

**Issue by Evertt** [sveltejs/svelte-preprocess#316]
**Is your feature request related to a problem? Please describe.**
I'm currently using svelte-preprocess to be able to use both typescript and postcss in my Sapper project. And I use postcss both for tailwind and for plugins like postcss-nested. Now I've been trying to replace tailwind with windicss, but I can't find a way to do combine it with svelte-preprocess and postcss.

**Describe the solution you'd like**
It'd be nice to have built-in support for windicss in such a way that it can be used in conjunction with postcss. Such that my styles can be both processed by plugins like postcss-nested *and* be compiled by windicss.

**Describe alternatives you've considered**
I haven't considered other solutions, because I don't understand very much of how the whole preprocessing works and so I have no clue how to get this to work if I wouldn't be able to use svelte-preprocess.

**How important is this feature to you?**
I can live with not using windicss for now. But in the end I'd really love to be able to use windicss, because it's faster, more streamlined, and has more features than tailwindcss.

**Comment by kaisermann** [comment]
Hey, @Evertt 👋  I wasn't aware of `windicss` (in fact, I was thinking of building something quite similar 😄). Svelte accepts an [array of preprocessors](https://svelte.dev/docs#svelte_preprocess), so you can run `svelte-preprocess` first and [`svelte-windicss-preprocess`](https://www.npmjs.com/package/svelte-windicss-preprocess) after it. 

Example:

```
// svelte.config.js
const sveltePreprocess = require("svelte-preprocess");
const windicss = require("svelte-windicss-preprocess");

module.exports = {
	preprocess: [sveltePreprocess(), windicss()]
};
```

I'm not 100% sure if this will work, but in theory, it should.

**Comment by Evertt** [comment]
@kaisermann thanks for responding. So I tried that and then what happens is that svelte throws errors during the compilation process.

And now I realize that that's probably a bug of windicss, because when I comment the windicss part out then it doesn't throw any errors anymore... Then it just doesn't process the classes and `@apply` rules anymore...

**Comment by kaisermann** [comment]
Can you make a repro?

**Comment by Evertt** [comment]
@kaisermann sure, this is my project where I'm trying to make it work in:

https://github.com/Evertt/sapper-cms/tree/windicss

I'm sure it's a bug from windicss, I'm just not sure what bug exactly.

**Comment by kaisermann** [comment]
Sorry for taking this long to look at the repo. Do you happen to have a minimal reproducible example? The one you shared is quite complex.

**Comment by non25** [comment]
I think `windicss` requires full markup to be passed in.

Here's the solution for a cool `cssModules` preprocessor, which uses svelte internal parser: https://github.com/micantoine/svelte-preprocess-cssmodules/#svelte-preprocess

By the way, could we integrate functionality provided by [svelte-as-markup-preprocessor](https://github.com/firefish5000/svelte-as-markup-preprocessor) into `svelte-preprocess` in the form like

```js
sveltePreprocess({
  postcss: true,
  postprocess: [
    cssModules(),
    whiteSpace()
  ]
})
```

?

**Comment by silasabbott** [comment]
For anyone using SvelteKit that comes across this issue, here's how to install WindiCSS:
1. If you're migrating from TailwindCSS, follow [these instructions first](https://windicss.org/guide/migration.html). If you aren't migrating, skip this step.
2. Follow [the official instructions to add WindiCSS to SvelteKit](https://windicss.org/integrations/svelte.html#sveltekit). It's super easy: you just drop the WindiCSS plugin into svelte-preprocess.

**Comment by kaisermann** [comment]
> "you just drop the WindiCSS plugin into svelte-preprocess."

Quick correction: `into svelte's preprocess option`, not in `svelte-preprocess`.

---

I now think that supporting Windicss out-of-the-box is out of the scope of `svelte-preprocess` and its current setup is fairly easy to do.
