### ISSUE TITLE
scss option prependData doesn't work

### ISSUE THREAD

**Issue by nipinium** [sveltejs/svelte-preprocess#317]
Turn out sass-loader has replaced `prependData` with `additionalData` from v9.0 onward: https://github.com/webpack-contrib/sass-loader#additionaldata

It's also doesn't work when I try using svelte-kit.

I think it's because of this commit: https://github.com/sveltejs/svelte-preprocess/commit/bc34b44ddd23061df17cd0b8ae04c44c4b74d904#diff-ff6ecd55841a6c9acd25a36810a2c548d5f682516175d7f1533551990ab9af0d

Should we just revert this? This stopped being an issue since sass-loader ignores the `prependData` option now.

**Comment by kaisermann** [comment]
I'm aware of that change in `sass-loader`. However, we don't use any code from it. The current supported property (for any language in fact) is the `prependData`: https://github.com/sveltejs/svelte-preprocess/blob/main/src/modules/prepareContent.ts#L20

There's an [open issue](https://github.com/sveltejs/svelte-preprocess/issues/280#issuecomment-726802470) to implement something like the `additionalData`

**Comment by nipinium** [comment]
@kaisermann maybe it's just me, but I try the prependData option on a new svelte-kit project and it doesn't seem to do anything.
Maybe I'd try it again and find out.

**Comment by nipinium** [comment]
I have just tried to use it with a new svelte-kit project and it works :)
Sorry for the wrong assumption.
