### ISSUE TITLE
[!] Error: Could not resolve './Other/other.svelte' from src\App.svelte

### ISSUE THREAD

**Issue by rengga21** [sveltejs/svelte-preprocess#329]
I have no idea with this bug, can someone help me to this issues.
i can't run the server.
![svelte bug](https://user-images.githubusercontent.com/38938319/111018816-c9bc9800-83ed-11eb-95ec-c77c5588ba10.PNG)

**Comment by rengga21** [comment]
> I have no idea with this bug, can someone help me to this issues.
> i can't run the server.
> ![svelte bug](https://user-images.githubusercontent.com/38938319/111018816-c9bc9800-83ed-11eb-95ec-c77c5588ba10.PNG)

**Comment by kaisermann** [comment]
Hey, @rengga21 👋  Please don't ignore the issue template. This doesn't seem to have any relation to `svelte-preprocess`. If you still have this problem, feel free to share a repro.

**Comment by rengga21** [comment]
Hey, @kaisermann  thanks for the advice, this issues is already solved.
