### ISSUE TITLE
{ sourceMap: false } does not work with typescript

### ISSUE THREAD

**Issue by trash-and-fire** [sveltejs/svelte-preprocess#330]
**Describe the bug**
It seems like `sourceMap: false` does not work with `lang="ts"` files.

**To Reproduce**
Run following code:
```js
const {preprocess} = require('svelte/compiler');

const file = `
<script lang="ts">
    export let counter: number = 0;
</script>
{counter}
`;

preprocess(file, require('svelte-preprocess')({sourceMap: false}), { filename: 'file.svelte' }).then((output) => {
    console.log('Output:');
    console.dir(output);

    console.log('Output contains source map url: ', output.code.includes('sourceMappingURL'));
});
```
`output.map` is not null and `output.code` contains `//# sourceMappingURL=file.svelte.js.map`

**Expected behavior**
`sorceMap: false` should not emit source maps and should not write source mapping url into the output code.

**Information about your project:**

- `svelte-preprocess` version 4.6.9

**Comment by kaisermann** [comment]
Hey, @trash-and-fire 👋  I've copied your code and got `false` with the current version of `svelte-preprocess`. Can you update and try again? 

![image](https://user-images.githubusercontent.com/12702016/118060625-8b017a80-b369-11eb-8d0f-e138079b02ec.png)

**Comment by trash-and-fire** [comment]
I've updated packages:
```
"svelte-preprocess": "4.7.3"
"svelte": "3.38.2"
```
Output does not contain `//# sourceMappingURL=file.svelte.js.map`.

Thank you.
