### ISSUE TITLE
TypeScript `Object is possibly 'null'` error

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/svelte-preprocess#331]
**Describe the bug**
The following code:
```
<script lang="ts">
  type User =  { name: any } | null
  let user: User = {
    name: new Promise((resolve) => {
      setTimeout(() => {
        resolve('probablykasper')
      }, 1000)
    })
  }
</script>

{#if user}
  {#await user.name}
    Loading username
  {:then name}
    Username: {name}
  {/await}
{/if}
```

results in this TypeScript error:
![image](https://user-images.githubusercontent.com/11315492/111087841-2fab3b80-8524-11eb-8327-a6c5ba787d5e.png)

**To Reproduce**
Repo: https://github.com/probablykasper/svelte-typescript-possibly-null

**Expected behavior**
When `await user.name` is inside an `if user` block, `user` cannot be null, so there should not be any TypeScript warning

**Information about your project:**

- Browser: N/A

- OS: macOS 10.14.6

- `svelte-preprocess` version: 4.6.9

- Bundler: Snowpack

**Comment by kaisermann** [comment]
Hey @probablykasper 👋  The IDE diagnostics come from the [language tools](https://github.com/sveltejs/language-tools). `svelte-preprocess` just transpiles your code to JS.
