### ISSUE TITLE
pug preprocessor doesn't support spread props

### ISSUE THREAD

**Issue by icheer** [sveltejs/svelte-preprocess#332]
**Describe the bug**
pug preprocessor doesn't support spread props

**Logs**
Syntax Error: Unexpected token

**To Reproduce**
```javascript
<template lang="pug">
input({...props})
</template>

<script>
let props = {
  type: 'number',
  disabled: true
};
</script>
```

**Expected behavior**
it should render a <  input type="number" disabled /    > in HTML

**Information about your project:**

- Your browser and the version: Chrome/89.0.4389.82

- Your operating system: Win10

- `svelte-preprocess` version 4.6.9

- Rollup

**Comment by paradis-A** [comment]
+1 up for this.

**Comment by paradis-A** [comment]
Your code actually works on mine. I think this issue maybe [language tools](https://github.com/sveltejs/language-tools/issues/806) related. AFAIK isn't fully supported yet,  so might want to  try to raise issue [there](https://github.com/sveltejs/language-tools/) too.

**Comment by ZerdoX-x** [comment]
Bumped in the same thing. Got `Syntax Error: Unexpected token`

Usage case:
```
ul.slider: +each('slides as slide')
  li.slide: svelte:component(this="{slide.comp}" {...slide.props})
```

**Comment by kaisermann** [comment]
Putting it between quotes `"` should be enough to make it work. Unfortunately, pug support for svelte syntax is quite weak at the moment.

So this:
```svelte
<template lang="pug">
  ul.slider: +each('slides as slide')
    li.slide: svelte:component(this="{slide.comp}" "{...slide.props}")
</template>
```

Will be transformed into:

```svelte
<ul class="slider">
  {#each slides as slide}<li class="slide">
    <svelte:component this="{slide.comp}" {...slide.props}></svelte:component></li>
  {/each}
</ul>
```

**Comment by kaisermann** [comment]
I've added a section in the `preprocessing.md` file: https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#:~:text=e)%20%3D%3E%20doTheThing(e)%7D%22)-,Spreading%20props%3A,-To%20spread%20props

**Comment by ClaytonFarr** [comment]
@kaisermann It looks like an 'unexpected token' error still occurs when trying to use ...$$restProps, even when it is double quoted.

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1226545/120942642-92594100-c6e7-11eb-899a-e65b682d36d4.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1226545/120942647-97b68b80-c6e7-11eb-8717-5c827f0d29ee.png">

 This is with: svelte-preprocess 4.7.3, svelte 3.38.2, and SvelteKit 1.0.0-next.112

**Comment by kaisermann** [comment]
@ClaytonFarr I'm unable to reproduce the error with that markup.

**Comment by ClaytonFarr** [comment]
Thanks for checking @kaisermann. Odd, it's still creating the 'unexpected error' even when I try to implement same markup as test -

<img width="896" alt="image" src="https://user-images.githubusercontent.com/1226545/121540379-ab057780-c9c3-11eb-8e7e-f8e71b3e9df5.png">

Here's a sample repo from a skeleton SvelteKit project that reproduces the problem (at least locally), if that helps.

**Comment by kaisermann** [comment]
Oh, I see! That's happening only on the IDE side, so I'd talk with the folks in the [language tools](https://github.com/sveltejs/language-tools/issues) repo. If I'm not mistaken, there's a known issue regarding pug and other markup languages. 

The generated markup is:
```
<button class="big" type="button" disabled {...$$restProps}>Send</button>

**Comment by ClaytonFarr** [comment]
Thanks @kaisermann

**Comment by kingcw** [comment]
still having "Unexpected Token" error on "{...$$restProps}" using pug in sveltekit@next, it's not IDE, I ran build script on linux terminal

**Comment by geoidesic** [comment]
Me too @kaisermann Doesn't compile for me.
