### ISSUE TITLE
<svelte:head> <style> tags being transformed

### ISSUE THREAD

**Issue by ryanfiller** [sveltejs/svelte-preprocess#333]
**Describe the bug**
This seems to be trying to apply transformations to inline style tags.

```
<svelte:head>
  {@html `<style> ... </style>`}
</svelte:head>

```

**Logs**
This results in this error: `CssSyntaxError: Unknown word`

**To Reproduce**
This is reproducible on any existing repo if you dump a style tag in the `@html` directive.

**Expected behavior**
It would be nice if this _didn't_ happen, or at least if there was some way to to manually exclude these?

**Information about your project:**
- Your operating system: OS X 10
- `svelte-preprocess` version `4.6.9`
- Rollup

**Comment by ryanfiller** [comment]
For what its worth, `preserve` doesn't seem to work here either.

I've got this in my Sapper config —
```
	sveltePreprocess({
		preserve: ['leave-me-alone-sapper']
	})
```

But this still errors.
```@html `
    <style type='text/leave-me-alone-sapper'>
      ...
    </style>
  `}
  
  I've narrow it down to that its trying to call a JS frunction withing the <style> tag that's the issue: 
  ```
  {@html `<style>${functionThatRendersAString()}</style>`}
  ```

**Comment by ryanfiller** [comment]
Just in case someone in the future is searching for this — I do not love this answer, but this is an answer.
 
You can break `svelte-preprocess`'s RegEx match like this
{@html `<${'style'}>${functionThatRendersAString()}</${'style'}>`}

Neat. Closing this issue.

**Comment by kaisermann** [comment]
Hey, @ryanfiller 👋  Unfortunately this is a limitation of Svelte itself. The compiler users RegExp to look for the script and style tags
