### ISSUE TITLE
Can't get VScode syntax working for SASS

### ISSUE THREAD

**Issue by geoidesic** [sveltejs/svelte-preprocess#334]
Hi there,

Great plugin! 
I can't get it to recognise SASS indent syntax though... what's the trick?
I've got preprocess set in rollup config and the svelte compiler is happy enough... it's just my eyes that are hurting in VScode now.
![Screenshot 2021-03-18 at 01 27 52](https://user-images.githubusercontent.com/4637995/111559849-3090d700-8789-11eb-977e-cf11bd59f93c.png)

**Comment by kaisermann** [comment]
Hey @geoidesic 👋  Do you have a `svelte.config.js` file? See [here](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/usage.md#with-svelte-vs-code)

**Comment by kaisermann** [comment]
This wouldn't be a `svelte-preprocess` issue either way, as we don't do anything regarding syntax highlighting.
