### ISSUE TITLE
Defaulting script to typescript breaks types

### ISSUE THREAD

**Issue by pikeas** [sveltejs/svelte-preprocess#335]
**Describe the bug**
```
module.exports = {
    preprocess: sveltePreprocess({
        defaults: {
            script: "typescript",
            style: "postcss",
        },
    }),
    ...
}
```

Works:
```
<script lang="ts">
    let count: number = 0
</script>
```

Errors:
```
<script>
    let count: number = 0
</script>
```

It can be fixed by replacing `typescript` with `ts` in the config. Are there two different transformers? If so, what are the differences between them, and which should be used?

**Expected behavior**
[Docs](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#auto-preprocessing-options) work as described, `<script>` supports all Typescript syntax without `lang` attribute.

**Information about your project:**

- Latest OSX, sveltekit (1.0.0-next.58), and preprocess (4.6.9).

**Comment by kaisermann** [comment]
Hey, @pikeas 👋  That shouldn't be happening. `ts` is considered an alias of `typescript` and should be working properly. Can you share a repro project?

**Comment by dummdidumm** [comment]
[Possibly related](https://github.com/sveltejs/language-tools/issues/916), but can't reproduce this either

**Comment by pikeas** [comment]
This seems to be a Heseinbug - it went away as I tried to make a clonable repro. I'll reopen if it happens again.
