### ISSUE TITLE
svelte, typescript, pnpm, monorepo: error TS6059: File '../../libs/package-name/src/Component.svelte' is not under 'rootDir'

### ISSUE THREAD

**Issue by btakita** [sveltejs/svelte-preprocess#336]
Using pnpm, typescript, sapper, svelte: after updating to `svelte-preprocess` `4.7.0`: a typescript `error TS6059` occurs.

```
error TS6059: File '../../libs/package-name/src/Component.svelte' is not under 'rootDir' '/path/to/project/libs/package-name/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
```

**Comment by trash-and-fire** [comment]
When the current working directory is not the same as the `rootDir` in tsconfig I get the same error even on version 4.9.2.

For example: my `cwd` is `.` and `rootDir: './src/package'`:
```
error TS6059: File '/sources/project/file.svelte' is not under 'rootDir' ''/sources/project/src/package'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
````
I don't know why it is trying to find `file.svelte` in `cwd` while it is in `./src/package`.

**Comment by dummdidumm** [comment]
Please create a separate issue about it so it can be tracked properly.
