### ISSUE TITLE
Upgrade from 4.6.9 to 4.7.0 results in TypeError

### ISSUE THREAD

**Issue by pglezen** [sveltejs/svelte-preprocess#339]
**Describe the bug**
Upgrading from `4.6.9` to `4.7.0` broke my (previously working) rollup build with the following error:

```
[!] (plugin svelte) TypeError: The "path" argument must be of type string. Received undefined
```

I had upgraded several packages.  So I reverted and upgraded them one at a time.  The build failure
started occurring after the `svelte-preprocess` upgrade.

**To Reproduce**
Upgrade from `4.6.9` to `4.7.0`:

```
$ npm run build:ui

> auditbrowser@1.0.0 build:ui
> rollup -c


src/UI/index.ts → dist/mainWin/bundle.js...
(!) Plugin typescript: @rollup/plugin-typescript: Typescript 'sourceMap' compiler option must be set to generate source maps.
created dist/mainWin/bundle.js in 1.9s
$ npm outdated
Package                  Current  Wanted  Latest  Location                              Depended by
@rollup/plugin-commonjs   17.1.0  17.1.0  18.0.0  node_modules/@rollup/plugin-commonjs  auditbrowser
svelte-preprocess          4.6.9   4.7.0   4.7.0  node_modules/svelte-preprocess        auditbrowser
$ npm upgrade svelte-preprocess

changed 1 package, and audited 978 packages in 2s

33 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ npm run build:ui

> auditbrowser@1.0.0 build:ui
> rollup -c


src/UI/index.ts → dist/mainWin/bundle.js...
[!] (plugin svelte) TypeError: The "path" argument must be of type string. Received undefined
src/UI/App.svelte
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.isAbsolute (path.js:1029:5)
    at loadTsconfig (/node_modules/svelte-preprocess/dist/transformers/typescript.js:45:27)
    at transformer (/node_modules/svelte-preprocess/dist/transformers/typescript.js:70:11)
    at Object.transform (/node_modules/svelte-preprocess/dist/autoProcess.js:37:12)
    at /node_modules/svelte-preprocess/dist/autoProcess.js:109:29
    at script (/node_modules/svelte-preprocess/dist/autoProcess.js:137:33)
    at process_single_tag (/node_modules/svelte/src/compiler/preprocess/index.ts:160:21)
    at async Promise.all (index 0)
    at replace_in_code (/node_modules/svelte/src/compiler/preprocess/replace_in_code.ts:72:23)
```

**Expected behavior**
I expected the build to succeed as it did in version `4.6.9`.

**Information about your project:**

This are the package versions I use that work (before upgrading to `4.7.0`).

```
$ npm ls
auditbrowser@1.0.0 /Users/pglezen/cjis/auditbrowser
├── @aws-sdk/client-dynamodb@3.11.0
├── @aws-sdk/util-dynamodb@3.11.0
├── @rollup/plugin-commonjs@17.1.0
├── @rollup/plugin-node-resolve@11.2.1
├── @rollup/plugin-typescript@8.2.1
├── @tsconfig/node14@1.0.0
├── @tsconfig/svelte@1.0.10
├── electron-store@7.0.2
├── electron@12.0.2
├── rollup-plugin-css-only@3.1.0
├── rollup-plugin-livereload@2.0.0
├── rollup-plugin-svelte@7.1.0
├── rollup-plugin-terser@7.0.2
├── rollup@2.44.0
├── svelte-check@1.3.0
├── svelte-preprocess@4.6.9
├── svelte@3.37.0
├── ts-node@9.1.1
└── tslib@2.1.0
```

**Additional context**
Node version:
```
$ node --version
v14.16.0
```

**Comment by pglezen** [comment]
This may be related to [this Svelte issue](https://github.com/sveltejs/svelte/issues/6159) reported a few days ago.

**Comment by pglezen** [comment]
After looking through the call stack, I see this might be related to an unorthodox reference to my **tsconfig** file.  In my `rollup.config.js`, my plugins are defined as listed below.  I'm specifying `tsconfig-ui.json` as my config file.  (I use a different one for my Electron main process).  I tried replacing the entry with an explicit relative path `./tsconfig-ui.json`.  But I received the same result.
```

export default {
  input: 'src/UI/index.ts',
  output: {
    sourcemap: true,
    format: 'iife',
    name: 'app',
    file: 'dist/mainWin/bundle.js'
  },
  plugins: [
    svelte({
      preprocess: sveltePreprocess({ sourceMap: !production }),
      compilerOptions: {
        dev: !production
      }
    }),
    css({ output: 'bundle.css' }),

    resolve({
      browser: true,
      dedupe: ['svelte'],
    }),
    commonjs(),
    typescript({
      tsconfig: 'tsconfig-ui.json',
      sourceMap: !production,
      inlineSources: !production,
    }),

    !production && serve(),
    !production && livereload('dist'),

    production && terser()
  ],
  watch: {
    clearScreen: false
  }
};
``` 

Finally, I added the location of the config file to the preprocessor configuration:
```
      preprocess: sveltePreprocess({ 
        sourceMap: !production,
        typescript: {
          tsconfigFile: 'tsconfig-ui.json'
        }
      }),
```
my config is resolved and the build succeeds.

Is it a bug that I now have to specify the location of my TS config file in two places?
* once for the TypeScript plugin
* once for the Svelte preprocessor

It's not that big of a deal.  But I didn't need to do it in version `4.6.9`.

**Comment by rdmurphy** [comment]
I think I'm getting a variation of this in #341. I get the same `TypeError`, but in my case I do not have a `tsconfig.json` file at all.

**Comment by kaisermann** [comment]
Hey, @rdmurphy and @pglezen 👋  Could you provide a minimal repro? I have an idea of what's going on but I can't seem to reproduce it on a test

**Comment by pglezen** [comment]
Hi @kaisermann .  Thanks for taking a look.  Here is one way to reproduce the problem.

1. Create a new project from the template.

   ```console
   $ npx degit sveltejs/template i339
   ```

2. Change to `i339` and install dependencies.

   ```console
   $ npm install
   ```

3. Enable TypeScript for the project.

   ```console
   $ node scripts/setupTypeScript.js
   ```

4. Install additional dependencies.

   ```console
   $ npm install
   ```

5. Rename `tsconfig.js`.

   ```console
   $ mv tsconfig.js tsconfig-ui.js
   ```

6. Add the name change to `rollup.config.js`.

   ```js
     //   ------ snip -------
   	plugins: [
		svelte({
	  preprocess: sveltePreprocess({ 
          sourceMap: !production,
          tsconfigFile: 'tsconfig-ui.json'
        }),
		compilerOptions: {
			// enable run-time checks when not in production
			dev: !production
		}
	}),
		// we'll extract any component CSS out into
		// a separate file - better for performance
		css({ output: 'bundle.css' }),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration -
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: ['svelte']
		}),
		commonjs(),
		typescript({
            tsconfig: 'tsconfig-ui.json',
			sourceMap: !production,
			inlineSources: !production
		}),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),
        // ---- snip ------
   ```
   Sorry that tabs and spaces conspired to mess up the formatting above.

7. Run build.

   ```console
   $ npm run build

   > svelte-app@1.0.0 build
   > rollup -c

   src/main.ts → public/build/bundle.js...
   [!] (plugin svelte) TypeError: The "path" argument must be of type string. Received undefined src/App.svelte
   ```

8. Back-level `svelte-preprocess`.

   ```console
   npm install svelte-preprocess@4.6.9
   ```

9. Rerun build.  It should work.

**Comment by kaisermann** [comment]
#345 should fix the overall issue 🎉 

Also, `tsconfigFIle` should be defined insided a `typescript` property:

```diff
      preprocess: sveltePreprocess({
        sourceMap: !production,
+        typescript: {
          tsconfigFile: "tsconfig-ui.json",
+        },
      }),
```

After adding it the build passes.

**Comment by pglezen** [comment]
Indeed, the additions you suggest above **does remove the error**.  I wonder if we can make the [TypeScript configuration documentation](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#typescript) clearer on that point.  I see now that **TypeScript** being the section title implies that `typescript` should be the property name of the configuration block.  But that's not obvious.  Perhaps just an example showing something like
```js
preprocess: sveltePreprocess({ 
  sourceMap: !production,
  typescript: {
    tsconfigFile: 'tsconfig-ui.json'
  }
}),
```
might serve to remove ambiguity.

**Comment by kaisermann** [comment]
@pglezen Not that I disagree, but we kind of explain how to configure an internal preprocessor [here](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#configuring-preprocessors). However, I'm completely open to suggestions on how we can improve this.
