### ISSUE TITLE
svelte-kit, typescript, error: "The requested module does not provide an export name"

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/svelte-preprocess#340]
**Is your feature request related to a problem? Please describe.**
I'm using Svelte Kit and the amazing [protobuf-ts](https://github.com/timostamm/protobuf-ts).

I'm having this error:

![image](https://user-images.githubusercontent.com/41120635/113699533-fbb3d800-96d5-11eb-8e24-33a0d72cc33a.png)

As [@timostamm noted](https://github.com/timostamm/protobuf-ts/issues/94#issuecomment-814191068) this error is due to this new [`svelte-preprocess`'s Typescript limitation](https://github.com/sveltejs/svelte-preprocess/issues/206).

But **that makes it frustrating if not impossible to work** with libraries like @timostamm's amazing one.

**Describe the solution you'd like**
I don't know! :(

**Describe alternatives you've considered**
I tried to change and remove `.tsconfig`'s `importsNotUsedAsValues` prop but the error is still there.

**How important is this feature to you?**
I'm pretty worried.

We CANNOT change each generated file every time we re-generate.

**Additional context**
This is the example repo: https://github.com/frederikhors/protobuf-ts-issue-94.

I'm using Win 10 64, node v14.16.0, npm v7.8.0.

**Steps to reproduce**:
- clone it with `git clone https://github.com/frederikhors/protobuf-ts-issue-94.git`

- `npm install`

- `npm run dev -- --open`

- click on "Protobuf" top menu link

- the error shows up

**Please HELP ME!**

**Comment by bluwy** [comment]
Should be fixed by #392

**Comment by dummdidumm** [comment]
Seems like the issue was with the autogenerated file not using `import type` where needed (type-only imports) and that issue was fixed in the library. Therefore this should be closed.
