### ISSUE TITLE
Consider exporting `AutoPreprocessOptions`

### ISSUE THREAD

**Issue by emme1444** [sveltejs/svelte-preprocess#344]
**Is your feature request related to a problem? Please describe.**

It would be nice if I could use a docstring to type the `sveltePreprocess` functions options object in the `svelte.config.{js,cjs}` file. Like so:

```js
module.exports = {
  ...
  preprocess: sveltePreprocess(
    /** @type {import('svelte-preprocess').AutoPreprocessOptions} */
    {
      defaults: {
        script: "typescript",
      },
      postcss: true,
    },
  ),
  ...
};
```

**Describe the solution you'd like**

Export the `AutoPreprocessOptions` interface.

**Describe alternatives you've considered**

None.

**How important is this feature to you?**

Okay-ish important, but very helpful and useful nonetheless.

**Additional context**

- I don't know if the `AutoPreprocessOptions` interface would be the correct one, but I looks like it to me anyway!

Thanks!

**Comment by kaisermann** [comment]
Hey, @emme1444 👋  Nice suggestion! WIll do it later today

**Comment by emme1444** [comment]
@kaisermann Sounds great! Glad I could help!

**Comment by kaisermann** [comment]
You should be able to `import { AutoPreprocessOptions } from 'svelte-preprocess/types'` in v4.7.1 🎉

**Comment by emme1444** [comment]
Awesome! Thanks!
