### ISSUE TITLE
<style lang="scss" global> doesn't work

### ISSUE THREAD

**Issue by iburning** [sveltejs/svelte-preprocess#351]
Hey, @YogliB 👋 that's happening because putting a `@use` rule inside a `:global {}` rule is not a valid in `sass`. The global attribute/selector preprocessor os executed after scss transforms your content, so it needs to be able to parse a valid scss code. You can try using the global attribute.

```svelte
<style lang="scss" global>
  ...
</style>
```

_Originally posted by @kaisermann in https://github.com/sveltejs/svelte-preprocess/issues/314#issuecomment-778774363_

I want to make a common component like a button.

```
<style lang="scss" global>
  my-button {
    // ...
  }
</style>
```

then, I want to change some style in different parent component.

but, it doesn't work, the my-button still has a svelte-xxx class name

**Comment by kaisermann** [comment]
Hey @iburning, can you provide a repro? From my understanding that should be working.

**Comment by c-bandy** [comment]
`postcss` needs to be installed [as documented](https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#globalstyle) for `<style global>` to work. Is it installed?

**Comment by AlexGalays** [comment]
I have a similar issue, with or without `postcss` installed, and whether `postcss` is installed as a dev or prod dependency. In fact I don't even see the warning if it's not installed.

The issue on my side is that an imported scss file (and it's own imports) see all its declarations marked as unused even with the `global` attribute on the `style` tag.

**Comment by gyurielf** [comment]
Same issue here.
Postcss installed and well configured.
But I got scoped classes for my ``<style lang="scss" global>`` styles.

**Comment by kaisermann** [comment]
Tested this locally and it should be working. Closing it for now 🙏
