### ISSUE TITLE
Use with sveltekit

### ISSUE THREAD

**Issue by johndeighan** [sveltejs/svelte-preprocess#367]
**Is your feature request related to a problem? Please describe.**
It's a problem for me, but maybe the answer is No?

**Describe the solution you'd like**
Documentation on usage with sveltekit, which doesn't use rollup.

**How important is this feature to you?**
Very important. sveltekit is the future of svelte.

**Comment by danitatt** [comment]
Coffeescript does not work with svelte-kit =(

**Comment by kaisermann** [comment]
Hey, @johndeighan and @danitatt 👋 We recently added a section to the docs/usage page: https://github.com/sveltejs/svelte-preprocess/blob/main/docs/usage.md#with-svelte-config

You mainly need to add your preprocess configuration to your `svelte.config.js` file

**Comment by danitatt** [comment]
@kaisermann Hello 👋🏼 In docs use `require`, but `svelte.config.js` support `import` ("type": "module" in package.json).
When use in `preprocess defaults: {}` options, svelte-kit crash. I use `defaults pug/sass/coffee`. In svelte it works fine, but in svelte-kit...
