### ISSUE TITLE
CSS module generates empty style

### ISSUE THREAD

**Issue by JeromeDeLeon** [sveltejs/svelte-preprocess#372]
**Describe the bug**
The problem is that it generates an empty style with the hash class name to the root element of the component when I tried to use the Svelte + Vite setup.
![svelte+vite steup](https://user-images.githubusercontent.com/32805276/121834137-92b59580-cd00-11eb-9045-1992b6ecc071.png)

It also happens when I tried to set up a clean project with `@svelte/kit`.
![image](https://user-images.githubusercontent.com/32805276/121834191-b7117200-cd00-11eb-8ddf-744b4d0256de.png)

**Logs**
_n/a_

**To Reproduce**
- Generate project using `npm init @vitejs/app <project_name> --template svelte-ts` or
- Generate project using `npm init svelte@next <project_name>`

**Expected behavior**
It shouldn't generate a class name where it doesn't need to

**Stacktraces**
_n/a_

**Information about your project:**

- Your browser and the version: MS Edge 91.0.864.48

- Your operating system: Windows 10

- `svelte-preprocess` version: 4.7.3

- Whether your project uses Webpack or Rollup: Rollup I think for Vite?

**Additional context**
It doesn't happen when using REPL.

**Comment by JeromeDeLeon** [comment]
Seems like all elements under components contains generated class name as seen on those pictures.

**Comment by kaisermann** [comment]
Hey, @JeromeDeLeon 👋 Are you able to reproduce this in a plain svelte project? I'm not sure this is related to `svelte-preprocess`.

**Comment by JeromeDeLeon** [comment]
This is my first time using it so I'm not sure if I would be able to produce it in a plain svelte project but REPL doesn't have this issue. Also, I'm not even sure where to raise it as this one is also appearing when you do any of the above instructions of reproduction to either vite or `@svelte/kit`, but `@svelte/kit` is using vite then it must have been vite issue. I'll try to relate this on `@svelte/kit` as well if that will help.
