### ISSUE TITLE
Typescript in template code

### ISSUE THREAD

**Issue by redmagic** [sveltejs/svelte-preprocess#378]
**Describe the bug**
I am using a nullish coalescing operator in template code, like so `<span>{$someStore.someProperty ?? ''}</span>`

**Logs**
Nothing special is logged

**To Reproduce**
Clone from https://github.com/redmagic/transpile-template-code
`npm i`
`npm start`
Inspect file dist/main.js and search for "123", here you can see the `??` is not transpiled

**Expected behavior**
The operator should be transpiled like here: https://www.typescriptlang.org/play?target=2#code/MYewdgziA2CmB00QHMAUBXMATWAzAlmLFgAQD8ZJATAJRA

**Comment by kaisermann** [comment]
Hey @redmagic 👋 

Currently using typescript in expressions inside your markup is not supported. This is kind of being discussed on: https://github.com/sveltejs/svelte-preprocess/issues/318

**Comment by redmagic** [comment]
Hi there!

Thanks for your quick reply, I'll keep an eye on that disscussion, closing this.
