### ISSUE TITLE
TypeScript processor reads and parses tsconfig for each processed file; target is not respected

### ISSUE THREAD

**Issue by cbxp** [sveltejs/svelte-preprocess#383]
**Describe the bug**
For performance reasons, tsconfig should be read only once per project. This can be verified in the debugger.
Also, target from tsconfig should be respected. Currently it is hardcoded to 'es6' no matter what tsconfig specifies.

**Information about your project:**

- `svelte-preprocess` version 4.7.3
- Whether your project uses Webpack or Rollup: Snowpack

**Workaround for setting target in config:**

```preprocess({typescript: {compilerOptions: {target: 'esnext'}}})```

However, something still re-processes it again, at least when using Snowpack. Will investigate more.

**Comment by kaisermann** [comment]
Hey, @cbxp 👋  There's definitely room for improving the `tsconfig` parsing. PRs are welcome! Unfortunately, I don't have the necessary time to focus too much on `svelte-preprocess` right now. 

Now, for the `target` issue, that's a bit easier to fix. However, we have to check what is the most modern Javascript version the Svelte compiler supports. `es6` was used right after the release of svelte v3

**Comment by dummdidumm** [comment]
Caching of the config is implemented, the target fix is pending.

**Comment by dimfeld** [comment]
It looks like [Svelte is passing `ecmaVersion: 12` to acorn](https://github.com/sveltejs/svelte/blob/c040f130b761a6aae64590999516adec5bb89680/src/compiler/parse/acorn.ts#L4-8), which according to the acorn docs corresponds to ES2021. So  ES2021 could be the best default target setting. Probably worth testing with whatever features are new in ES2021 to make sure though.

**Comment by dummdidumm** [comment]
Bumping the target which unconditionally overwrites the user-defined target would be a breaking change, so the fix should contain logic that assigns the target if isn't present in the user's `tsconfig`.
