### ISSUE TITLE
v4.9 broke accessing stores with $ prefix when imported in module context

### ISSUE THREAD

**Issue by joaopaulobdac** [sveltejs/svelte-preprocess#401]
Hey, everywhere in my code where I access store values using the $ prefix now cause an `is not defined` error similar to https://github.com/sveltejs/svelte-preprocess/issues/396.

I'm using `"svelte-preprocess": "^4.9.2"` and `"typescript": "^4.4.2"`.

I have to set the svelte-preprocess version back to 4.8.0 to fix it.

**Comment by dummdidumm** [comment]
Could you provide a minimum reproducible / code snippet ?

**Comment by joaopaulobdac** [comment]
I'm using SvelteKit v1.0.0-next.164:

```svelte
<script lang="ts">
  import { session, signOut } from "$lib/session"
</script>

{#if $session}
  <button on:click|once={signOut}>Sair</button>
{:else}
  <a href="/entrar">Entrar</a>
{/if}
```

`session` is a custom store actually:

```ts
import { writable } from "svelte/store"

export function createLocalStorage(key: string) {
  const { subscribe, set } = writable<string | null>(
    localStorage.getItem(key),
    (set) => {
      function handleStorageEvent(event: StorageEvent) {
        if (event.key === key) {
          set(event.newValue)
        }
      }
      window.addEventListener("storage", handleStorageEvent)
      return () => window.removeEventListener("storage", handleStorageEvent)
    }
  )

  return {
    subscribe,
    set: (value: string | null) => {
      set(value)
      if (value) {
        localStorage.setItem(key, value)
      } else {
        localStorage.removeItem(key)
      }
    },
    get: () => localStorage.getItem(key)
  }
}

export const session = createLocalStorage("session")
```

**Comment by dummdidumm** [comment]
Given your code snippet and using the latest version of SvelteKit I'm unable to reproduce this (I added `signOut` to your code snippet because it was missing).

**Comment by joaopaulobdac** [comment]
Ah I think I found the actual issue. You need to import the value in a `context="module"` script.
Try changing `<script lang="ts">` to `<script lang="ts" context="module">`.

I'm sorry for this sloppy bug report, I was in a hurry and assumed any code snippet containing the store would do.

**Comment by dummdidumm** [comment]
Still can't reproduce it. I addded `context="module"` and the code compiles and works.

**Comment by janaz** [comment]
I came across the same issue. This is how I import and use the store in my page component in sapper

```svelte
<script lang="ts" context="module">
import store from "./store"
</script>

<script lang="ts">
// using $store here causes the error "ReferenceError: store is not defined"
console.log($store)
</script>

```

**Comment by joaopaulobdac** [comment]
:x: When I add `context="module"` I get an error:
```svelte
<script lang="ts" context="module">
  import { session, signOut } from "$lib/session"
</script>

{#if $session}
  <button on:click|once={signOut}>Sair</button>
{:else}
  <a href="/entrar">Entrar</a>
{/if}
```
![20210909060513](https://user-images.githubusercontent.com/62244135/132657146-64866e03-de26-4541-97c6-f26441a2055f.png)

:heavy_check_mark: If I use the store in the component script everything works:
```svelte
<script lang="ts" context="module">
  import { session, signOut } from "$lib/session"
</script>

<script lang="ts">
  console.log($session)
</script>

{#if $session}
  <button on:click|once={signOut}>Sair</button>
{:else}
  <a href="/entrar">Entrar</a>
{/if}
```

:x: But then if I don't use the store in the template, I get an error:
```svelte
<script lang="ts" context="module">
  import { session } from "$lib/session"
</script>

<script lang="ts">
  console.log($session)
</script>

<div>Some template</div>
```
![20210909060917](https://user-images.githubusercontent.com/62244135/132657697-128d0bec-f535-4da0-bac5-061032be4a5a.png)

:heavy_check_mark: Finally if I move the import to the component script it works again:
```svelte
<script lang="ts">
  import { session } from "$lib/session"
  console.log($session)
</script>

<div>Some template</div>
```

**Comment by dummdidumm** [comment]
Thanks, can reproduce this now. The error occurs when there's a `$store` subscription where `store` is imported in the module script.

The IDE error of the first error case is unrelated to this, I'll open a ticket in language-tools for this.
