### ISSUE TITLE
Typescript processing breaks when tsconfig has `outDir` set

### ISSUE THREAD

**Issue by dimfeld** [sveltejs/svelte-preprocess#405]
**Describe the bug**

When `outDir` is set in tsconfig.json, Typescript generates a `sourceMapChain` with a bad path for the `sources` in the source map, which leads to an ENOENT error somewhere in `sorcery` when it tries to open the file.

**Logs**

I finally traced it down to this `sourceMapChain` (extraneous bits omitted)

```js
{
  filename: '/home/dimfeld/cv/code/apps/data-admin-tool/src/routes/customer_usage/index.svelte',
  sourcemaps: {
     '/home/dimfeld/cv/code/apps/data-admin-tool/src/routes/customer_usage/index.svelte.injected.ts': SourceMap {
   version: 3,
   file: 'index.svelte.injected.ts',
   sources: [ 'index.svelte' ],
   sourcesContent: [ null ],
   },
    '/home/dimfeld/cv/code/apps/data-admin-tool/src/routes/customer_usage/index.svelte.transpiled.js': {
   version: 3,
   file: 'index.svelte.injected.js',
   sourceRoot: '',
   // Here's the bad value
   sources: [ '../src/routes/customer_usage/index.svelte.injected.ts' ],
}
```

which leads to this error:
```
Error: ENOENT: no such file or directory, open '/home/dimfeld/cv/code/apps/data-admin-tool/src/routes/src/routes/customer_usage/index.svelte.injected.ts'
```

Note the double `src/routes` that comes from resolving the `sources` value. When `outDir` is not set, the sources value is just `['index.svelte.injected.ts']`.

**To Reproduce**

Build https://github.com/dimfeld/svelte-preprocess-injected-bug

**Expected behavior**

Doesn't crash.

**Information about your project:**

- svelte-preprocess 4.9.4, reproduces on >= 4.9.0. I think the underlying issue was there before but the older source map processing didn't actually throw an exception.
- svelte 3.42.4
- Ubuntu 21.04
- Whether your project uses Webpack or Rollup -- Reproduces on both.

**Additional context**

In my case this happens in a monorepo when loading Svelte components from another package that also contains regular Typescript files, so outDir is set in a package for compiling those files. Most normal Svelte projects wouldn't be using outDir so this probably doesn't come up much.

I think the best course of action here is for the typescript transformer to alter the loaded Typescript configuration to remove outDir unconditionally. Happy to submit a PR if you agree.

**Comment by dummdidumm** [comment]
If we just omit `outDir`, will this produce source maps which point to the correct source then? I'm having a hard time thinking this through, since `svelte-preprocess` is just part of a larger chain of compilations, and what role `outDir` plays in this circumstance.

**Comment by dimfeld** [comment]
Sorry if the original description is unclear. this isn’t a problem of incorrect generated source maps in the final output. The problem is that when outDir is set, svelte-preprocess throws an exception.

This is due to the internally generated source maps with injected.ts and transpired.js having bad paths which sorcery chokes on in `concatSourceMaps`, since Typescript setd the path to the injected.ts file as if it had written it to `<packageRoot>/<outDir>/filename.injected.ts` instead of just `filename.injected.ts`. 

Sorcery then tries to open that file and since it’s a different path from the correct virtual module path for injected.ts it goes to the actual file system and fails to open the nonexistent file, causing an exception and build failure. 

Im on mobile now but happy to provide more details later if the description here and the reproduction are still unclear.

**Comment by dummdidumm** [comment]
Thank you for the explanation. What I meant - expressed myself poorly - is if the source map url is then different/wrong, and if it even matters since other transformers (Svelte->JS) run afterwards. The source mappings itself should be unaffected by this, as you said.

**Comment by dimfeld** [comment]
Ah, got it. Yes, in my testing clearing outDir has no negative effect on the correctness of the source map output. 

I think this actually fixes another less obvious bug too. Svelte's preprocess code has a check for the `sources` matching what it expects, and when outDir is set this check actually fails.

https://github.com/sveltejs/svelte/blob/c040f130b761a6aae64590999516adec5bb89680/src/compiler/preprocess/index.ts#L82-L86

Running svelte-preprocess with `handleMixedImports` disabled allows it to run without crashing, and I observed the following at this point in the code.

Without clearing outDir, Svelte will not match `file_basename` to `sources`:
```
{ file_basename: 'App.svelte', sources: [ '../../src/App.svelte' ] }
{
  file_basename: 'Button.svelte',
  sources: [ '../../src/component/Button.svelte' ]
}
```

With outDir cleared, they will match:
```
{ file_basename: 'App.svelte', sources: [ 'App.svelte' ] }
{ file_basename: 'Button.svelte', sources: [ 'Button.svelte' ] }
```

So now the check passes and the offsets are updated appropriately.

**Comment by dummdidumm** [comment]
Thank you for your investigation! This makes sense, the `outDir` is something that yields correct results if TS is the only tool in the mix when building TS->JS files. With Svelte files, there's another step (rollup-plugin-svelte for example) needed, so rewiring the source urls before that is too early. Your PR therefore should be a good fix for both these issues.
