### ISSUE TITLE
script lang ts dont see import svelte component

### ISSUE THREAD

**Issue by jerryk1925** [sveltejs/svelte-preprocess#409]
i have some problem with typescript and svelte, my svelte component dont see import file (css, svelte and other)
```
<script lang="typescript">
    import Qwe from './qwe.svelte'
</script>

<div >
    <Qwe />
</div>
```

```
Error
WARNING in ./src/App/index.svelte
Module Warning (from ./node_modules/svelte-loader/index.js):
'Qwe' is not defined (9:4)
```

package.json
`{
  "name": "marno",
  "version": "1.0.0",
  "description": "",
  "main": "main.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "svelte": "3.42.6"
  },
  "devDependencies": {
    "@babel/core": "7.15.5",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.13.0",
    "@babel/plugin-transform-runtime": "7.15.0",
    "@babel/preset-env": "7.15.6",
    "@babel/preset-typescript": "7.15.0",
    "@babel/runtime": "7.15.4",
    "@tsconfig/svelte": "2.0.1",
    "babel-loader": "8.2.2",
    "core-js": "3.17.3",
    "css-loader": "^3.6.0",
    "html-webpack-plugin": "5.3.2",
    "mini-css-extract-plugin": "2.3.0",
    "postcss": "8.3.5",
    "postcss-import": "14.0.2",
    "postcss-loader": "4.3.0",
    "postcss-nested": "5.0.5",
    "postcss-preset-env": "6.7.0",
    "style-loader": "3.2.1",
    "svelte-loader": "3.1.2",
    "svelte-preprocess": "4.9.4",
    "ts-loader": "9.2.5",
    "typescript": "4.4.3",
    "webpack": "5.52.1",
    "webpack-cli": "4.8.0",
    "webpack-dev-server": "4.2.1"
  },
  "author": "",
  "license": "ISC"
}
`

webpack rule
```
            {
                test: /\.(js|ts|mjs|svelte)$/,
                exclude: /node_modules\/(!svelte)/,
                use: ['babel-loader'],
            },
            {
                test: /\.svelte$/,
                exclude: /node_modules/,
                use: {
                    loader: 'svelte-loader',
                    options: {
                        hotReload: true,
                        emitCss: true,
                        preprocess: require('svelte-preprocess')({
                            postcss: postcssConfig,
                            typescript: true
                        })
                    }
                }
            },
            {
                test: /node_modules\/svelte\/.*\.mjs$/,
                resolve: {
                    fullySpecified: false
                }
            },
```
tsconfig

```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "CommonJS",
    "lib": [
      "DOM",
      "ES5"
    ],
    "isolatedModules": true,
    "allowJs": true,
    "importsNotUsedAsValues": "remove",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "baseUrl": ".",
    "skipLibCheck": true,
    "paths": {
      "marno/*": ["src/*"]
    },
    "types": [
      "svelte",
      "svelte/store",
      "svelte/motion",
      "svelte/transition",
      "svelte/animate",
      "svelte/easing"
    ]
  }
}
```

**Comment by lagunovsky** [comment]
You need to change the "module" option to es2015 or older

**Comment by ikudosi** [comment]
This has been driving me nuts! Thank you for pointing out it's due to the stupid lang attribute that's been throwing me off. Literally spent 1 day trying different configurations with webpack. Changing the `"module: commonjs" ` to `"module: es6"` did not work for me either.

**Comment by kaisermann** [comment]
This doesn't seem to be related to `svelte-preprocess`. Closing it 🙏
