### ISSUE TITLE
Deprecate type=".." and several lang=".."

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/svelte-preprocess#414]
**Is your feature request related to a problem? Please describe.**
Right now it's possible to signal that TS is used in 4 ways
- `lang="ts"`
- `lang="typescript"`
- `type="text/ts"`
- `type="text/typescript"`

The first of these is the recommended way, and Vite only accepts this version (see https://github.com/vitejs/vite/pull/5105 for more). It's confusing to have multiple ways to express the same and puts the burden on all other tools to check these four values.

**Describe the solution you'd like**
Deprecate all `type=".."` usages. Deprecate `lang="typescript"` and `lang="javascript"`. Remove handling these in 5.0

**Describe alternatives you've considered**
Deprecate, but don't remove

**How important is this feature to you?**
Not important now, but important in the long run for standardization

**Comment by kaisermann** [comment]
I'm 100% on board with this. Deprecating the `type` variant should be easy enough. The `lang` on other hand, is not that simple. Partially done in #417.
