### ISSUE TITLE
Support other languages through WebAssembly

### ISSUE THREAD

**Issue by TheHadiAhmadi** [sveltejs/svelte-preprocess#420]
**Is your feature request related to a problem? Please describe.**
this is not related to problem and it is a feature request (or question)

**Describe the solution you'd like**
I want to ask is it possible to build preprocessor for languages that is supported by web assembly?
there will be need for a compiler as dev dependency for building the module
and after compiling result will be a wasm module linked to svelte app.

for most cases writing code in compiled languages like rust, c and c++ is more performant than javascript
and will increase performance.

for example have 

```svelte
<script lang="c">
int add_two(int a, int b) {
    return a + b;
}
</script>
<script>
    let sum = add_two(5, 3)
</script>
<p>{sum}</p>
```

**Describe alternatives you've considered**
alternative is writing everything in javascript

thanks

**Comment by kaisermann** [comment]
Hey @TheHadiAhmadi 👋. Svelte only supports the usual script tag, which represents code ran when instantiating the component, and the `context="module"` one. This means that having a `lang="c"` implies that your whole component code will be written in C. To do what you described, it would be better to add WASM support to your bundler/workflow instead.
