### ISSUE TITLE
autoPreprocess is removing `<template>` tags from the output

### ISSUE THREAD

**Issue by jguze** [sveltejs/svelte-preprocess#422]
**Describe the bug**
`autoPreprocess` seems to be stripping out `<template>` tags in Svelte components, which then renders their contents to the screen immediately. [Templates](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) should not render to the screen automatically.

If you remove autoPreprocess from rollup, it will work as expected.

**To Reproduce**
I've created a repro using the generic Svelte template. You can see I added two things: `autoPreprocess` into rollup, and a `<template>` tag in App.svelte.

https://github.com/jguze/svelte-preprocess-template-bug/blob/main/src/App.svelte#L11

When you run the app using `npm run dev`, you'll notice the contents within the `<template>` tag appear on screen. Inspecting the source code shows that the `<template>` tag is completely removed. 

**Expected behavior**
`<template>` tag remains in the output

**Information about your project:**

- All browsers
- `svelte-preprocess` version - 4.9.8
-Rollup

**Comment by mustafa0x** [comment]
Can this be disabled?

**Comment by kaisermann** [comment]
For now you need to change the markupTagName or use specific processors instead of the automatic one.
