### ISSUE TITLE
New lang="coffee" doesn't always work when deprecated type="text/coffeescript" syntax works.

### ISSUE THREAD

**Issue by Leftium** [sveltejs/svelte-preprocess#436]
**Describe the bug**
New `lang="coffee"` doesn't always work when deprecated `type="text/coffeescript"` syntax works.

A syntax error *intermittently* results because the CoffeeScript is processed as plain JavaScript.

**Logs**
Please see https://github.com/sveltejs/kit/issues/2920

**To Reproduce**
Please see https://github.com/sveltejs/kit/issues/2920

**Expected behavior**
Scripts with `lang="coffee"` are always processed as CoffeeScript.

**Information about your project:**
Please see https://github.com/sveltejs/kit/issues/2920

- SvelteKit (Vite + Rollup)

**Additional context**
Please see https://github.com/sveltejs/kit/issues/2920

**Comment by bluwy** [comment]
As explained in https://github.com/sveltejs/kit/issues/2920, we can close this issue in favour of that one.

**Comment by Leftium** [comment]
> I was able to fix this by changing lang="coffee" to the deprecated type="text/coffeescript" syntax. With the newer lang attribute, some part of build sometimes doesn't recognize the script is written in CoffeeScript.

This makes me wonder if it's actually a svelte-preprocess issue.

**Comment by Leftium** [comment]
Closing in favor of https://github.com/sveltejs/kit/issues/2920

> The `lang` to `type` workaround is still a Kit/Vite issue, as the scanner has special handling for the `lang` attribute, so setting `type` only bypasses it.

**Comment by Leftium** [comment]
A work-around is to move the CoffeeScript outside the index.svelte file into its own _index.coffee file. Then use an external script tag like:

    <script src='./_index.coffee'></script>

I confirmed this works with the latest SvelteKit on Vercel:
- https://feh-shing-m8frybxpj-leftium.vercel.app/
- https://github.com/Leftium/FEHshing/commit/1b696760ace1c2ffdc5de8fdbbb4d1f4e83b7a8b

(The version with inline coffeescript still results in a build error on Vercel, even though there was none locally):
- https://github.com/Leftium/FEHshing/commit/dfae5358603eff27a26afd9c025de7fa2a62b0e3
