### ISSUE TITLE
Trying to import a coffeescript file doesn't work

### ISSUE THREAD

**Issue by ivands** [sveltejs/svelte-preprocess#444]
I'm trying to import a coffeescript file inside my .svelte file.
```
<script lang="coffee">
	import File from './other.coffee'
</script>
```
or
```
<script>
	import File from './other.coffee';
</script>
```

Both examples are not working.
The following error is returned:
```[vite] Error when evaluating SSR module /src/lib/File.svelte: Parse failure: Unexpected token```

I've defined ```svelte-preprocess``` in my svelte config file and I have added coffeescript to my package.

I'm using the following verions:
    "@sveltejs/kit": "next",
    "coffeescript": "^2.6.1",
    "svelte": "^3.44.0",
    "svelte-preprocess": "^4.10.0"

Can someone tell me what I'm doing wrong?

**Comment by bluwy** [comment]
The error is coming from SvelteKit/Vite. Currently they do not support Coffeescript in Svelte files, so I'd suggest avoiding that at the meantime until Vite fully supports it, but it would take a long while to reach there.

I think we can close this as it's not related to svelte-preprocess.
