### ISSUE TITLE
YAML and JSON5 imports?

### ISSUE THREAD

**Issue by eden-omb** [sveltejs/svelte-preprocess#450]
**Is your feature request related to a problem? Please describe.**
I like taking out small data bits like list items and such to external files to import and e.g. iterate over. Right now I can only use .json or .js files, which are nice I guess but meh.

**Describe the solution you'd like**
Well, being able to import .yaml and .json5 files would be way more convenient.

**Describe alternatives you've considered**
I tried to get [vite-plugin-yaml](https://github.com/clemvnt/vite-plugin-yaml) to work, but keep getting weird errors when I add it to `kit.vite.plugins` in `svelte.config.js`.

**How important is this feature to you?**
It'll be pretty neat! For little data bits in pages and such, and more importantly for i18n files and modules. Not a deal breaker or anything though, it's about as annoying as having to use raw JSON.

**Comment by bluwy** [comment]
This doesn't sound like an issue in svelte-preprocess. I'd recommended asking in Vite or SvelteKit's GitHub discussion, or discord. It would also be helpful if you can show what the weird errors are.

**Comment by eden-omb** [comment]
Oh for sure, this is a feature request to have these supported as part of
this package. It certainly seems on-theme, even if it is out of scope. I'd
enjoy it working out of the box, so to speak.

**Comment by dummdidumm** [comment]
Not 100% sure if this is a worthwhile addition. It seems rather niche to not use JSON for these things. Adding support might make people think they then could use it outside of Svelte files, too, which wouldn't be the case.
Getting a rollup/vite/webpack plugin to work seems like a better solution to me right now.

**Comment by eden-omb** [comment]
Hmm I see, I wasn't aware of that limitation. I'll look into the vite plugin then. Thanks a bunch!
