### ISSUE TITLE
[sass] preprocess mixes legacy and current api

### ISSUE THREAD

**Issue by bato3** [sveltejs/svelte-preprocess#452]
**Describe the bug**
The [render and renderSync](https://sass-lang.com/documentation/js-api/modules#renderSync) methods have been marked as legacy. The svelte-preprocess expose [configuration options](https://github.com/sveltejs/svelte-preprocess/blob/f6ef334f45c1327e087d031bd6f3791970d7cd25/src/types/options.ts#L2) from new way.

From sass:
```ts
export function renderSync(options: LegacyOptions<'sync'>): LegacyResult;

export function render(
  options: LegacyOptions<'async'>,
  callback: (exception?: LegacyException, result?: LegacyResult) => void
): void;
```
new way:
```ts
export function compile(path: string, options?: Options<'sync'>): CompileResult;
```

**Comment by kaisermann** [comment]
This is being fixed in #562
