### ISSUE TITLE
Error in svelte.config.js - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by flyingduck92** [sveltejs/svelte-preprocess#454]
**Describe the bug**
Error in svelte.config.js
SyntaxError: Unexpected token 'export's

How to fix this issue? 

</details>

![image](https://user-images.githubusercontent.com/14885417/148163480-e174fcd7-ee14-439f-9845-8fa6ce27fa25.png)

![image](https://user-images.githubusercontent.com/14885417/148163494-c0bcffce-c724-469a-b557-2356a83ef6ba.png)

Other Informations:
node v14.18.2

**Comment by bluwy** [comment]
This isn't an issue in svelte-preprocess. You're likely not using `type: module` in `package.json`, so `import` statements doesn't work in `svelte.config.js`. You have three ways to fix this:

1. Use `require()` instead
2. Rename `svelte.config.js` to `svelte.config.mjs`
3. Set `type: module` in `package.json` (may break other scripts)

**Comment by flyingduck92** [comment]
@bluwy I fixed the issue by setting up **Svelte Language-server: Runtime on VSCode**
`File > Preferences > Settings` search `svelte` in searchbox, then find `Svelte > Language-server: Runtime`. 
After that, add full path to `node.exe`  (e.g: `C:\\Program Files\\nodejs\\node.exe`)

**Comment by dummdidumm** [comment]
I don't think this is the right fix, one of the suggestions of @bluwy should be preferred. Also make sure you have a recent VS Code version.

**Comment by flyingduck92** [comment]
@dummdidumm Why the readme **Svelte-with-VSCode** didn't mention to use `require()`, rename to `svelte.config.mjs`, and change `type: module` in `package.json`?

 **Svelte-with-VSCode** -  https://github.com/sveltejs/svelte-preprocess/blob/main/docs/usage.md#with-svelte-vs-code

But I found another page that mention to add `node.exe` to `Svelte Language-server: Runtime on VSCode` and just fixed my issue
