### ISSUE TITLE
Reference hash

### ISSUE THREAD

**Issue by gwet-stripe** [sveltejs/svelte-preprocess#460]
When setting any "mode", Svelte continues to inject a reference hash. How could I simply keep only the style hash without having a reference hash that I don't use.

![image](https://user-images.githubusercontent.com/91576265/148906121-711637a0-ecec-4d16-ad00-8fb5eb943530.jpeg)

![image](https://user-images.githubusercontent.com/91576265/148906134-8b228885-9b49-4722-a798-630123e4d782.jpeg)

Thanks guys, good job with cssmodule.

**Comment by bluwy** [comment]
The hash is injected by `vite-plugin-svelte` and is needed for HMR. It won't be there for production builds. If you don't want it for dev too, you have to disable `vite-plugin-svelte`'s HMR (not recommended)

**Comment by dummdidumm** [comment]
Closing as this is unrelated to `svelte-preprocess`
