### ISSUE TITLE
Pass tailwind's header files to postcss config

### ISSUE THREAD

**Issue by mustafa0x** [sveltejs/svelte-preprocess#462]
Tailwind requires:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Projects often have an "app.css" which just contain those lines. I'd like to avoid that if possible. Is there a way to pass that string into `svelte_preprocess({postcss: {plugins: [tailwind]}})` directly?

Note: they can't be added to App.svelte as they'll then be at the end of the outputted CSS instead of the start.

**Comment by dummdidumm** [comment]
Introducing a second way to do the same doesn't sound good to me. This might confuse people ("what is the right way?") and it's something we need to maintain in addition to the other stuff, which I'd like to avoid. So therefore I'm against this.

**Comment by mustafa0x** [comment]
Thanks for your reply. I agree, but was curious if there exists a way now to pass code directly to `svelte_preprocess` or postcss, perhaps using some lower-level api
