### ISSUE TITLE
Unreliable esbuild/typescript behaviour

### ISSUE THREAD

**Issue by endigma** [sveltejs/svelte-preprocess#472]
full details and reproduction in repo below:

https://gitlab.com/endigma/svelte-esbuild

**Comment by wiesson** [comment]
I'm not a maintainer, the provided information are looking quite less?

**Comment by endigma** [comment]
I've provided an entire repo documenting reproduction and information I have about the bug, including a workaround?

**Comment by kaisermann** [comment]
> I've provided an entire repo documenting reproduction and information I have about the bug, including a weird workaround?

Hey @endigma, can you put the description and repro on this Github issue? The easiest you make it for us to see your problem, the easier will be to detect the problem and fix it. 

[Also, that gitlab repo requires a sign-in.](https://user-images.githubusercontent.com/12702016/151656120-24d2cfe0-7279-4ceb-a1a7-a10d3345c9d0.png)

**Comment by endigma** [comment]
https://github.com/endigma/svelte-esbuild

&&

# svelte-esbuild bug reproduce conditions

when `typescript({ content }) {}` replacement is embedded into the automatic preprocessor, it fails with:

![](https://github.com/endigma/svelte-esbuild/blob/main/images/fail-1.png?raw=true)
![](https://gitlab.com/endigma/svelte-esbuild/-/raw/main/images/fail-1.png)

and 

![](https://github.com/endigma/svelte-esbuild/blob/main/images/fail-2.png?raw=true)
![](https://gitlab.com/endigma/svelte-esbuild/-/raw/main/images/fail-2.png)

when replacement is wrapped in `typescript()` from `svelte-preprocessor`, functions normally.

this seems almost nonsensical but it's reproducible.

## success

`rollup.config.js`
```js
// import spp from "svelte-preprocess";
// import { typescript } from "svelte-preprocess"
// ...
preprocess: [
    typescript({
        typescript({ content }) {
            const { code, map } = transformSync(content, {
                loader: "ts",
            });
            return { code, map };
        }
    }),
    spp({
        typescript: false
    }),
],
// ...
```

## fail

`rollup.config.js`
```js
// import spp from "svelte-preprocess";
// ...
preprocess: [
    spp({
        typescript({ content }) {
            const { code, map } = transformSync(content, {
                loader: "ts",
            });
            return { code, map };
        }
    }),
],
// ...
```

# run

```sh
git clone git@gitlab.com:endigma/svelte-esbuild.git
cd svelte-esbuild

yarn install
yarn dev # or yarn build
```

**Comment by endigma** [comment]
@kaisermann

**Comment by dummdidumm** [comment]
ESBuild does not know anything about the surrounding of the script tag that is handed to it, it will therefore remove all unused imports if not told otherwise through a tsconfig (there is none in the reproduction repo). This means default imports of Svelte components are also removed.
You need to add a `tsconfig` and enable `preserveValueImports` to change this behavior. This flag was (also) added for Svelte for precisely this use case: https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names

Closing as this is nothing under our control.

**Comment by endigma** [comment]
That's nonsense, it works when called through `import { typescript } from "svelte-preprocess"` ?

**Comment by dummdidumm** [comment]
`typescript` from `svelte-preprocess` is an entirely different preprocessor. In your example you switch our the built-in preprocessor with your own preprocessor, so you have to do tsconfig lookup and making sure it's preprocessed correctly etc yourself.
