### ISSUE TITLE
TypeScript parsing in markup

### ISSUE THREAD

**Issue by blaumeise20** [sveltejs/svelte-preprocess#475]
**Describe the bug**
I would expect to have support for TypeScript syntax inside markup, but it doesn't work.
Example:
```svelte
<script lang="ts">
    let something: string | null = "hi";
</script>

<div>
    {something!.toUpperCase()}
    <!--      ^ error    -->
</div>
```

**To Reproduce**
Just copy the example from above

**Expected behavior**
Expressions inside markup should support syntax from the language specified in the script tag.

-----

The problem here is that if you put the script tag below the markup (what some people do), you couldn't know it while parsing. So we would need to either use `svelte:options` or just not allow other syntax if the script tag is below markup.

**Comment by Conduitry** [comment]
See https://github.com/sveltejs/svelte/issues/4701 - this is not currently possible and there are some hurdles in Svelte core to overcome first.

**Comment by dummdidumm** [comment]
Svelte 5 will support TS (types-only, i.e. not enums etc that need to be transpiled to something else) in the template, therefore closing
