### ISSUE TITLE
Replace transformer replaces only the first occurrence of the string

### ISSUE THREAD

**Issue by wereHamster** [sveltejs/svelte-preprocess#477]
**Describe the bug**

When I use the replace transformer (to inject `process.env.FOO` into the code), only the first occurrence of that expression is replaced. So if I use the expression multiple times, it leads to runtime crashes.

**To Reproduce**

```
sveltePreprocess({
  replace: [
    ["process.env.FOO", "FOO"],
  ],
});
```

and use `process.env.FOO` multiple times in the code.

**Expected behavior**

All occurrences are replaced (equivalent to replaceAll or the global flag in regexp). I don't see how replacing only the first occurrence would be useful.

**Additional context**

The call to replace in the transformer is here: https://github.com/sveltejs/svelte-preprocess/blob/881f3c9ad6118fb66b560494a67042944567e0ec/src/transformers/replace.ts#L14. 

The `String.prototype.replaceAll()` function is available in Node 15+.

**Comment by dummdidumm** [comment]
As you can see from the code, you can pass in a regular expression and solve your use case this way: `/process\.env\.FOO/g`

**Comment by wereHamster** [comment]
I know how to work around it. I'm just curious why the default is to only replace the first occurrence, since that is not what users expect (IMO). The [docs](https://github.com/sveltejs/svelte-preprocess#replace-values) make no mention of that special behaviour.

I'd expect it to replace all occurrences by default.

**Comment by kaisermann** [comment]
@wereHamster Your expectation is not wrong. However, the `replace` preprocessor uses `string.replace()` behind the scenes and that's its default behavior. To replace all, one should pass a regexp and the `g` flag. We could change to `string.replaceAll` but that would up the node version requirement to `15.14.0`.
