### ISSUE TITLE
[idea] Drop node-sass support

### ISSUE THREAD

**Issue by bfanger** [sveltejs/svelte-preprocess#485]
**Is your feature request related to a problem? Please describe.**
`yarn install` fails on modern node versions.

https://sass-lang.com/blog/libsass-is-deprecated

**Describe the solution you'd like**
'sass' (dart-sass) is the recommended successor.
Which (aside from additional slash-div warnings) has been a nice experience
(didn't break when upgrading nodejs and is faster than ruby sass)

**Describe alternatives you've considered**
`nvm` & `docker run node:12`

**How important is this feature to you?**
Not important, I'm not a svelte-preprocess maintainer 😅

**Additional context**
I want to fix a bug in svelte-process, but had to jump through hoops to get `yarn dev` working.
Other potential contributors might have given up more easily.

**Comment by kaisermann** [comment]
Hey @bfanger 👋  sorry for the delay! This will be handled by #562
