### ISSUE TITLE
Imported ts file in an imported Svelte file looses typescript definition

### ISSUE THREAD

**Issue by mbakker96** [sveltejs/svelte-preprocess#489]
**Describe the bug**
When importing a typescript file from a .svelte file that is not included in the tsconfig. The compiler gives the error `Unexpected token`. It does not know anymore of he is importing a typescript file or a js file. We didn't add the share folder in our tsconfig because it is used by multiple projects and is full of typescript errors (strict mode). We only want to include files that are beging used via import. 

We have a project with multiple svelte projects inside. These projects share one package.json, but all have there own rollup, tsconfig and App.svelte. 

Does someone know of this is a bug or a mistake in the config? 

**Logs**
```
src/project-b/App.svelte → public/build/bundle.js...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/share/utils/utils.ts (2:28)
1: 
2: export function capatilize(s: string): string {
                               ^
3:   return s.toUpperCase()
4: }
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/martijn/Projects/typescript-probleem/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/Users/martijn/Projects/typescript-probleem/node_modules/rollup/dist/shared/rollup.js:12477:16)
    at Module.tryParse (/Users/martijn/Projects/typescript-probleem/node_modules/rollup/dist/shared/rollup.js:12853:25)
    at Module.setSource (/Users/martijn/Projects/typescript-probleem/node_modules/rollup/dist/shared/rollup.js:12756:24)
    at ModuleLoader.addModuleSource (/Users/martijn/Projects/typescript-probleem/node_modules/rollup/dist/shared/rollup.js:22220:20)
```

**To Reproduce**
I've created an example repo:

[https://github.com/mbakker96/svelte-bug/blob/main/README.md](https://github.com/mbakker96/svelte-bug/blob/main/README.md)

**Expected behavior**
Files are included when they are called in an import

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

Stack trace goes here...

</details>

**Information about your project:**

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10) 
- not applicable

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
- MacOS Monterey

- `svelte-preprocess` version (Please check you can reproduce the issue with the latest release!)
- ^4.0.0

- Whether your project uses Webpack or Rollup
- Rollup

**Additional context**

**Comment by OmarAlya** [comment]
Hello @mbakker96 , Did you find a solution for that ?

**Comment by AlexFeier** [comment]
I have a similar problem.
.svelt import a ts file.
ts file import a type 
" import type { .... "
This leads to the error Unexpect token.

Is there a solution for this ?

**Comment by dummdidumm** [comment]
Closing because repo is no longer available, and this was a very long time ago. If this persists please open a new issue.
