### ISSUE TITLE
reactive in coffeescript not work

### ISSUE THREAD

**Issue by gcxfd** [sveltejs/svelte-preprocess#491]
`$: y = x * 2` not work

```
<script lang="coffee">
import '~/styl/init.styl'
import logo from ':/svg/logo.svg'
import Counter from './lib/Counter.svelte'

x = 1

$: y = x * 2

click = =>
  ++x
  return
</script>

<template lang="pug">
main
  img(src="{logo}" alt="logo")
  button(on:click="{click}")
    +if('x%2') if x%2
      +else() else
  h2 x {x} y {y}
  Counter
</template>

<style lang="stylus">
button
  width 8rem
  font-size 32px

main
  justify-content center
  align-items center
  flex-direction column
  display flex

img
  height 16rem
  width 16rem
</style>
```

**Comment by mrkishi** [comment]
Some info after light digging: Coffeescript seems to [compile labels into blocks](https://coffeescript.org/#try:%24%3A%20hello%20%3D%20'world'%0A).

This seems unlikely to be fixable on this end as there are no compiler options to change that behavior.

**Comment by Conduitry** [comment]
Searching online for "svelte coffeescript", I just found https://github.com/Leftium/svelte-coffeescript-pug/blob/master/src/App.svelte which has a possible syntax for that will compile into the JS that Svelte needs for reactive blocks. It looks like it involves jumping out to JS syntax within CoffeeScript.

In short, I would not at all recommend writing Svelte components with CoffeeScript.

I'm going to close this issue, as this is functioning as (unfortunately) designed.

**Comment by gcxfd** [comment]
@mrkishi @Conduitry 

I write as patch https://github.com/rmw-lib/coffee-label-patch make coffeescript support label

but when I try merge this into svelte-preprocess , 

there is always error

```
src/transformers/coffeescript.ts:3:19 - error TS2307: Cannot find module '@rmw/coffee-label-patch' or its corresponding type declarations.
```


<img width="1920" alt="image" src="https://user-images.githubusercontent.com/69608605/160078914-46cb4505-826a-4c82-ad1d-ec5020c8313c.png">
