### ISSUE TITLE
Version 5 (major release) planning

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/svelte-preprocess#504]
This issue is intended to collect breaking changes we want to do for the next major version of `svelte-preprocess`. What currently comes to my mind:

- remove support for the default language (deprecated already)
- remove support for `lang="typescript"` and `type="text/..."` (deprecated already AFAIK)
- remove support for Node 10 (EOL) and 12 (EOL end of April)
- remove peer dependencies and instead tell in the docs what versions we tested it with. Npm 7 automatically installs peer dependencies, which means useless downloads for almost everyone. UPDATE: There's https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta so we can keep peer deps. We can do this now already.
- Only support the new SASS API (right now we only support the legacy API). This means bumping the peer dep.

**Comment by mcmxcdev** [comment]
You might want to add another bullet point to consider switching from yarn v1, which has frozen development for a while, to e.g. pnpm (which would be in line with the package manager choice of other sveltejs repos)

**Comment by kaisermann** [comment]
> This issue is intended to collect breaking changes we want to do for the next major version of svelte-preprocess. What currently comes to my mind:

I was hoping v5 would be released at a similar time as the RFCed new preprocess API, but it seems that's still far from happening. Removing deprecations and support for EOL node versions is a good start! We don't need to make it a very big breaking change 🤷

> You might want to add another bullet point to consider switching from yarn v1, which has frozen development for a while, to e.g. pnpm (which would be in line with the package manager choice of other sveltejs repos). 

I have no qualms with switching to another package manager, even more, if it's to the same one used by other Svelte projects.

**Comment by frangio** [comment]
Peer dependencies can be marked optional as shown here: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta

I believe this turns off the automatic installs.
