### ISSUE TITLE
HTML/XML compilant mode for HTML processing tools

### ISSUE THREAD

**Issue by locriacyber** [sveltejs/svelte-preprocess#505]
**Is your feature request related to a problem? Please describe.**
Current svelte markup language uses `{#if}` and confuses HTML parsers. Tools like [posthtml](https://www.npmjs.com/search?q=posthtml), [rehype](https://github.com/rehypejs/rehype) cannot be during preprocess directly.

**Describe the solution you'd like**
Encode the markup language into a XML format, pass to other tools to process, then decode when done.

**Describe alternatives you've considered**
None

Most tools work with HTML or XML can't parse svelte markup. Examples:
- rehype
- posthtml
- cheerio

**How important is this feature to you?**
I need to use posthtml to process the index page which has some interativity. The posthtml step need to process the svelte component markup.

**Current workaround: reference svelte.config.js**
```js
import adapter from "@sveltejs/adapter-static"
import preprocess from "svelte-preprocess"
import smartypants from "./smartypants.mjs"

/**
 * @param content  svelte script
 */
async function add_typography_to_html({ content, filename }) {
  let dependencies = []

  return {
    // hacky way, because there is no way to parse svelte script properly
    code: content.replace(/\<p\>.*?\<\/p\>/gm, (x) => smartypants(x, 1)),
    dependencies,
  }
}

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: [
    preprocess(),
    {
      defaultLanguages: { markup: "html" },
      markup: add_typography_to_html,
    },
  ],
  kit: {
    adapter: adapter(),
  },
}

export default config
```

**Comment by dummdidumm** [comment]
Adding some kind of HTML/XML transformation is out of scope. How should it even look like so that it makes sense semantically? Your workaround is a valid solution, you can use regex or the Svelte parser and traverse the AST to transorm the code as you wish.
