### ISSUE TITLE
Update PostCSS Load Config

### ISSUE THREAD

**Issue by spencermize** [sveltejs/svelte-preprocess#534]
**Is your feature request related to a problem? Please describe.**
Hey! PostCSS Load Config now supports ESM modules as of v4.0. It'd be great to get the deps updated here so we can continue moving away from `.cjs` files in SvelteKit.

**How important is this feature to you?**
Not super important, but I think it's the last `.cjs` domino to fall in my repo and would unlock some things I've been looking to do for awhile.

**Additional context**
(https://github.com/postcss/postcss-load-config/blob/main/CHANGELOG.md#40-2022-05-23)

Thanks!

**Comment by bluwy** [comment]
`postcss-load-config` v4 is supported in the latest release (https://github.com/sveltejs/svelte-preprocess/pull/520), and it's a peer dep, so you would have to bump it in your project yourselves.
