### ISSUE TITLE
Add Support For Markdown

### ISSUE THREAD

**Issue by PizzaNachos** [sveltejs/svelte-preprocess#549]
I would like to add a blog to my svelteKit website and statically render markdown text.

There are other svelte markdown preproscessors but having it in the "Official" one could help
Ex:
# Heading 1
## heading 2
->
<h1>Heading 1</h1>
<h2>heading 2</h2>
ect...

**Comment by kaisermann** [comment]
While the idea makes sense, I'm not sure how useful would a barebones markdown transformer be. I don't think a lot of people just want to render markdown without importing components, etc. With that in mind, I think it's better to use https://github.com/pngwn/MDsveX if one wants to add support for markdown in their svelte files.
