### ISSUE TITLE
chore(deps): update stylus to 0.59.0

### ISSUE THREAD

**Issue by katriellucas** [sveltejs/svelte-preprocess#553]
**Is your feature request related to a problem? Please describe.**
Level 4 CSS selector do not work on Stylus 0.55.0, (this was added on 0.58.0), since Stylus didn't reach 1.0 yet, major versions are still in middle numbers and being ignored, as of now, there is already a year gap since the latest release.

**Describe the solution you'd like**
Update Stylus to 0.59.0

**Describe alternatives you've considered**
There is no alternative solutions, it just has to be updated, maybe add support for minor versions? 

**How important is this feature to you?**
Note: Important, level 4 selector are used in part of my components, they don't work without them.

**Additional context**
Nothing to add.

**Comment by kaisermann** [comment]
Hey @katriellucas 👋  we don't force a specific stylus version. `stylus` is defined as a peer dependency with the following semver range: `^0.55.0`. This should allow you to install `0.59.0` without issues. What kind of issue are you having?

**Comment by dummdidumm** [comment]
PR for this welcome! The one doing that should manually check that the latest stylus version still works with our preprocessor API, and if so, change the peerDependency to `>=0.55`
