### ISSUE TITLE
@types/sass deprecated

### ISSUE THREAD

**Issue by mustofa-id** [sveltejs/svelte-preprocess#582]
**Describe the bug**
Get a deprecated warning when creating a new project with Sveltekit

**Logs**
` WARN  deprecated @types/sass@1.45.0: This is a stub types definition. sass provides its own type definitions, so you do not need this installed. `

```bash
$> pnpm why @types/sass
Legend: production dependency, optional only, dev only

my-project@0.0.1 /path/to/my-project

devDependencies:
svelte-check 3.0.4
└─┬ svelte-preprocess 5.0.1
  └── @types/sass 1.45.0
```

**Comment by kaisermann** [comment]
Should be fixed by #583. Released in `v5.0.2` 🎉
