### ISSUE TITLE
doc gap: compile a javascript variant via preprocess, apply to .ts

### ISSUE THREAD

**Issue by stylehouse** [sveltejs/svelte-preprocess#603]
**Is your feature request related to a problem? Please describe.**
Docs in this repo dont cover how to transform some source to javascript.
I have got something working for .svelte files. I want 'EXPR and BLOCK', etc.
By hijacking the 'typescript' alias (apparently to be deprecated?)  I keep my IDE basically understanding things inside: <script lang="typescript">

It seems like <script lang="anything"> (given alias etc) will be fed to javascript?

Can it apply to all my src/**.ts files?
Configuring a 'ts' alias doesn't bring them in.

Can I import ... from "$lib/Co" and resolve src/lib/Co.anything?

**Describe the solution you'd like**
To write in MyTypescriptSuperset with lang="ts" in components and .ts modules.
I know about standards and I agree this is a bit dodgy but it reduces change-all-tools-ness around new lang.

**Describe alternatives you've considered**
Frantic research of vite|svelte innards until I know heeeaps.
Externally compile anything until it's typescript (or so) to continuously deploy into Svelte... Whole other same exact system of development.

**How important is this feature to you?**
No problem.

**Additional context**
I've been journaling, which may be mined for words, after the cactus:
https://howsecologysquad.blogspot.com/2023/05/svelte-further-than-ever-before.html
And here are the transforms:
https://github.com/stylehouse/letz/blob/main/svelte.config.js
And the source that uses '# comments' etc which compile:
https://github.com/stylehouse/letz/blob/main/src/routes/Code.svelte#L112

**Comment by stylehouse** [comment]
I figured out:

> apply to .ts
svelte.config.js is where to specify a preprocess for .svelte files (and you must also compile the ts),
and vite.config.ts is where to plugin a plugin for .ts files (that you leave ts).

how to [compile_typescript_like_svelte()](https://github.com/stylehouse/letz/blob/971a24cc4722cc64d255d0d2381c5242cd9a93ea/src/lib/Compiler.js#L63)
and other [connective tissues](https://github.com/stylehouse/letz/blob/main/src/lib/Compiler.js)

this issue is now just doc compost
cheers

**Comment by dummdidumm** [comment]
General guidance on this topic can be found in the Svelte docs: https://svelte.dev/docs#compile-time-svelte-preprocess
Where to add the preprocessor depends on the bundler used, but svelte.config.js is correct for Vite/SvelteKit
