### ISSUE TITLE
Lightningcss support

### ISSUE THREAD

**Issue by mattpilott** [sveltejs/svelte-preprocess#616]
Vite now offers support for lightningcss, if i try to use this with svelte preprocess i get an error. Is this something this package could provide support for or is it elsewhere?

**Comment by dummdidumm** [comment]
`svelte-preprocess` does not directly support lightingcss. But vite-plugin-svelte version 3 has support for it via the vite preprocessor that ships with it: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md#vitepreprocess
