### ISSUE TITLE
Not compatilbe with postcss-load-config v5.x

### ISSUE THREAD

**Issue by BCsabaEngine** [sveltejs/svelte-preprocess#618]
**Describe the bug**
I use svelteKit with standard settings. After update postcss-load-config to 5.0.2 I see, that explicite imported svelte-process not exists. After try to install it, peer/normal dependency failed.

**To Reproduce**
Just upgrade postcss-load-config witn ncu to v5.0.2

**Expected behavior**
Works like the charm

**Comment by baseplate-admin** [comment]
There's already a PR for this : https://github.com/sveltejs/svelte-preprocess/pull/617
