### ISSUE TITLE
Support `pnpm@9`

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/svelte-preprocess#628]
**Is your feature request related to a problem? Please describe.**

The package is not compatible with the newly released [pnpm@9].

[pnpm@9]: https://github.com/pnpm/pnpm/releases/tag/v9.0.0

> This error happened while installing the dependencies of svelte-check@3.6.9
> 
> Your pnpm version is incompatible with "svelte-preprocess@5.1.3".
> 
> Expected version: ^8.0.0
> Got: 9.0.0
> 
> This is happening because the package's manifest has an engines.pnpm field specified.
> To fix this issue, install the required pnpm version globally.

**Describe the solution you'd like**

Support `"pnpm": ">= 8.0.0"` if possible.

https://github.com/sveltejs/svelte-preprocess/blob/c2107e529da9438ea5b8060aa471119940896e40/package.json#L20-L24

**How important is this feature to you?**

Blocking upgrade to [pnpm@9].

**Comment by shinokada** [comment]
Does anyone know how to downgrade `pnpm` to version 8 using `brew`?

**Comment by Ragavendaran** [comment]
Simpler downgrade way for pnpm installed in npm

```
pnpm setup

pnpm i -g pnpm@8
```

**Comment by shinokada** [comment]
When I use pnpm v9, I get the following errors:

```
.
├─┬ @sveltejs/vite-plugin-svelte 3.1.0
│ └─┬ svelte-hmr 0.16.0
│   └── ✕ unmet peer svelte@"^3.19.0 || ^4.0.0": found 5.0.0-next.106
├─┬ vite 5.2.9
│ └── ✕ unmet peer @types/node@"^18.0.0 || >=20.0.0": found 12.20.55
└─┬ vitest 1.5.0
  └── ✕ unmet peer @types/node@"^18.0.0 || >=20.0.0": found 12.20.55
```

Is it only me?
