### ISSUE TITLE
I get the "The engine "pnpm" appears to be invalid" warning when installing svelte-preprocess@5.1.3 with yarn

### ISSUE THREAD

**Issue by fromaline** [sveltejs/svelte-preprocess#630]
**Describe the bug**
I'm getting this weird non-critical bug, when installing `svelte-preprocess@5.1.3` with yarn:

```
warning svelte-preprocess@5.1.3: The engine "pnpm" appears to be invalid.
```

**To Reproduce**
```
yarn add svelte-preprocess
```

**Expected behavior**
I expected no warning at all

**Information about your project:**

- Your operating system: MacOS 14.2.1

- `svelte-preprocess` version 5.1.3

**Comment by dummdidumm** [comment]
Fixed through #629
