### ISSUE TITLE
 WARN  Issues with latest peer dependency postcss-load-config@6 found 

### ISSUE THREAD

**Issue by delight** [sveltejs/svelte-preprocess#634]
**Describe the bug**
A major version of postcss-load-config (6.0.0) got released. 
This is not included in the allowed versions of peerDependencies yet

**Logs**
 WARN  Issues with peer dependencies found
.
└─┬ svelte-check 3.8.0
  └─┬ svelte-preprocess 5.1.4
    └── ✕ unmet peer postcss-load-config@"^2.1.0 || ^3.0.0 || ^4.0.0 || ^5.0.0": found 6.0.0

**To Reproduce**
update svelte project dependencies to latest versions

**Expected behavior**
No warning on updates

**Information about your project:**

new sveltekit project

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
(x)buntu 22.04

- `svelte-preprocess` version (Please check you can reproduce the issue with the latest release!)
5.1.4

- Whether your project uses Webpack or Rollup
vite

I got the simple patch ready

**Comment by dummdidumm** [comment]
Closed as part of #640
