### ISSUE TITLE
⚠️ 3 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6, rimraf@2.7.1

### ISSUE THREAD

**Issue by Valexr** [sveltejs/svelte-preprocess#636]
3 deprecated subdependencies found: glob@7.2.3, inflight@1.0.6, rimraf@2.7.1

**Comment by Valexr** [comment]
<img width="338" alt="Screenshot 2024-06-06 at 07 09 48" src="https://github.com/sveltejs/svelte-preprocess/assets/5656366/ac881e34-896a-476f-8cdd-189bf79ee147">

**Comment by dummdidumm** [comment]
Fixed as part of #640
