### ISSUE TITLE
Replace sorcery

### ISSUE THREAD

**Issue by benmccann** [sveltejs/svelte-preprocess#637]
**Is your feature request related to a problem? Please describe.**

`sorcery` is outdated and unmaintained. It prints deprecation warnings for users. It also adds a dependency that isn't used elsewhere in the Svelte ecosystem

**Describe the solution you'd like**

Replace `sorcery` with `@ampproject/remapping` like we do in Svelte

https://github.com/sveltejs/svelte-preprocess/blob/276037a78b8b0e30d99d042e84dda61e79c3a918/src/transformers/typescript.ts#L263

https://github.com/sveltejs/svelte/blob/84ad208f2e986fa549683a12e7f999c3d31b127f/packages/svelte/package.json#L132

I wonder if we even need to combine source maps though? What is `injectVarsToCode` doing?

**Describe alternatives you've considered**

Update `sorcery`. But even then it'd be nice to have fewer dependencies in a new SvelteKit app

**How important is this feature to you?**

Important at the moment because it's causing https://github.com/sveltejs/kit/issues/12258

**Comment by benmccann** [comment]
This would fix https://github.com/sveltejs/svelte-preprocess/issues/636 as well

**Comment by benmccann** [comment]
We're fixing up `sander` right now, which makes this less necessary, but it'd still be nice to do to reduce the dependency footprint of `svelte-preprocess`

**Comment by dummdidumm** [comment]
This can be ripped out entirely as part of a major if we do one soon - this code is from a time when typescript didn't have good support for separating between value and type imports

**Comment by dummdidumm** [comment]
Removed as part of #640
