### ISSUE TITLE
@custom-media queries return `")" is expected` error

### ISSUE THREAD

**Issue by danrichman** [sveltejs/svelte-preprocess#644]
**Describe the bug**
`")" is expected` error returned when using [`@custom-media` queries](https://www.w3.org/TR/mediaqueries-5/#custom-mq).

**To Reproduce**
https://svelte.dev/repl/285764ff2bf3407994880659f22fb589?version=4.2.18

**Expected behavior**
`@custom-media` queries are [valid CSS](https://www.w3.org/TR/mediaqueries-5/#custom-mq) and should not return an error.

**Comment by dummdidumm** [comment]
This is a Svelte issue, not a `svelte-preprocess` issue. Svelte 5 will fix this, therefore closing.
