### ISSUE TITLE
DEPRECATION WARNING: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by Keavon** [sveltejs/svelte-preprocess#656]
**Describe the bug**
According to:
```
> npm ls sass
my-project
├─┬ svelte-preprocess@6.0.2
│ └── sass@1.79.3
└─┬ vite@5.4.7
  └── sass@1.79.3 deduped
```
This, together with Vite, both pull in Sass 1.79 which has begun spamming the console with deprecation warnings (see **Logs** in the next paragraph). Vite already has an issue open for this, https://reddit.com/r/opensource/comments/1fk4jot/whats_some_super_beautiful_open_source_uis, but I'm creating one here as well. They opted to downgrade to Sass 1.78 and that might be a viable solution here too.

**Logs**
The following is spammed repeatedly to the console:
> More info: https://sass-lang.com/d/legacy-js-api
> 
> DEPRECATION WARNING: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

**To Reproduce**
Use Sass in your Svelte 4 project and bundle it with Vite.

**Expected behavior**
No console spam.

**Information about your project:**

I'm running Windows 11 and [here is my package.json](https://github.com/GraphiteEditor/Graphite/blob/master/frontend/package.json). The problem occurs when all dependencies are fully up-to-date, but I'm avoiding upgrading for now until this issue is resolved.

**Comment by kaisermann** [comment]
@Keavon 

>  Vite already has an issue open for this, https://reddit.com/r/opensource/comments/1fk4jot/whats_some_super_beautiful_open_source_uis, but I'm creating one here as well. They opted to downgrade to Sass 1.78 and that might be a viable solution here too.

I think you pasted the wrong link 😅

**Comment by Keavon** [comment]
Indeed, I'm not sure how I didn't notice that was the wrong paste 🤔
