### ISSUE TITLE
Svelte 4 and 5 seem to have different defaults for scss compiler

### ISSUE THREAD

**Issue by kapooostin** [sveltejs/svelte-preprocess#659]
**Describe the bug**
I'm upgrading my project from Svelte 4 to 5. And the styling now fails as my environment (Adobe UXP) doesn't support some of the newer CSS syntax, which appeared after changing the Svelte version.

**Logs**
None

**To Reproduce**
I have the following

```svelte
<style lang="scss">
.set-layer-names {
  & > li {}
}
</style>
```

svelte.config:
```js
import { sveltePreprocess } from "svelte-preprocess";

export default {
  preprocess: sveltePreprocess( { typescript: false } ),
};
```

In Svelte 4 the style compiles to 
```css
.set-layer-names.svelte-f6o4w6>li.svelte-f6o4w6{}
```

And in Svelte 5—to
```css
.set-layer-names.svelte-f6o4w6 > li:where(.svelte-f6o4w6){}
```

**Expected behavior**

I guess the JS target for Svelte 5 also changed as I now need, for instance, to polyfill `queueMicrotask` to make it work in UXP, so the problem is specific to my use case. The modern versions of browsers probably support both new JS APIs and CSS selectors. Please, point me in the right direction on how to control the compilation of SCSS.

**Information about your project:**

- Your browser and the version: Adobe UXP 7.4

- Your operating system: OS X 14.6

- `svelte-preprocess` 6.0.3

- Vite 5.4.9

**Comment by Conduitry** [comment]
This is unrelated to Sass, and is simply how Svelte 5 scopes selectors now - see https://svelte-5-preview.vercel.app/docs/breaking-changes#other-breaking-changes-scoped-css-uses-where

**Comment by kapooostin** [comment]
Ok, thank you! Is it possible to apply this within `svelte-preprocess`?
```js
css = css.replace(/:where\((.+?)\)/, '$1');
```

**Comment by dummdidumm** [comment]
No, it needs to be a post compile step, i.e. you need to fiddle around with vite plugins. @dominikg anything easy how someone can hook into the build pipeline to achieve this?

**Comment by dominikg** [comment]
did you try using `vitePreprocess` instead and provide a browserslist config to postcss so it knows what syntax it has to downlevel?

**Comment by dummdidumm** [comment]
Will this work though? This has to happen after the compiler , not as a preprocessing step

**Comment by dominikg** [comment]
we'll have to check where the downleveling happens, i hope it is in a post step in vite:css because plugins (like vite-plugin-svelte) can emit css files.  vps is a pre plugin, so the css it emits should go through vites pipeline so i hope it just works.

if not you'd need to add a plugin targeting css emitted by vite-plugin-svelte and modify it in transform hook. cc @bluwy

**Comment by bluwy** [comment]
`:where` can't be downleveled without changing its specificity, so there's no easy way to do so with postcss or lightningcss as far as I know of. You can technically write a plugin to do so but you'd have to opt-in and acknowledge the change of specificity and semantics.

**Comment by dummdidumm** [comment]
Does it make sense to add a hook to v-p-s that's invoked with the compiled result before handing it back to vite?

```js
const result = svelte.compile(...)
const finalized = postProcess(result);
...
```

**Comment by dominikg** [comment]
why not a separate vite plugin?

**Comment by kapooostin** [comment]
> did you try using `vitePreprocess` instead and provide a browserslist config to postcss so it knows what syntax it has to downlevel?

Well, any nesting returns `where`, so I guess there isn't a target for PostCSS to account for this:
```css
h1 span {
  color: green;
}
```
as it is compiled to:
```css
h1.svelte-n6oght span:where(.svelte-n6oght) {
  color: green;
}
```

**Comment by kapooostin** [comment]
> why not a separate vite plugin?

I think, it would be ideal. I'll dig into Vite, as atm I have little idea about its plugins. Thanks!
