### ISSUE TITLE
Able to use node-sass-magic-importer?

### ISSUE THREAD

**Issue by ryburn52** [sveltejs/svelte-preprocess#99]
**Describe the bug**
Is it possible to use third party sass importers like [node-sass-magic-importer](https://www.npmjs.com/package/node-sass-magic-importer)?

This looks like it would solve some problems we are having where sass imports are bloating the build as well as issues importing from node_modules. 

When i configure the importers for the svelte-preprocess i get this error 

> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
>     at validateString (internal/validators.js:125:11)
>     at Object.dirname (path.js:646:5)
>     at Object.importer (C:\MyProject\node_modules\node-sass-magic-importer\src\index.ts:92:32)
>     at options.importer.(anonymous function) (C:\MyProject\node_modules\node-sass\lib\index.js:323:32)

**To Reproduce**
Using webpack to configure the sass-loader looks like this this.

```
                use: [
                    'style-loader',
                    { loader: 'css-loader', options: { sourceMap: true } },
                    {
                        loader: 'sass-loader',
                        options: {
                            sassOptions: {
                                importer: magicImporter()
                            }
                        }
                    }
                ]
```

This appears to work for normal sass files but when configuring the svelte preprocess like this i get the error above.

```
const magicImporter = require('node-sass-magic-importer');

.....

  {
                test: /\.svelte$/,
                use: {
                    loader: 'svelte-loader',
                    options: {
                        preprocess: require('svelte-preprocess')({
                            scss: {
                                importer: [
                                    magicImporter(),
                                ],
                            }
                        })
                    }
                }
            },
```

**Expected behavior**
Should be able to configure the sass importers the same way you would the sass-loader

**Information about your project:**
- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)
Window 10 
- `svelte-preprocess` version (Please check you can reproduce the issue with the latest release!)
3.2.5
- Whether your project uses Webpack or Rollup
Webpack

**Comment by nitro52** [comment]
I'm not sure if this is a Bug/Feature/Not Possible but i'm not sure how else to ask

**Comment by kaisermann** [comment]
Hey @nitro52 👋  Can you share a repro? I wasn't able to reproduce it on my side.

**Comment by nitro52** [comment]
@kaisermann I've pushed a changed to my [project template](https://github.com/nitro52/svelte-typescript-sass-template) that can reproduce the issue. 

under `webpack.common.js` just uncomment `magicImporter()` in the svelte preprocess setup

```
            {
                test: /\.svelte$/,
                use: {
                    loader: 'svelte-loader',
                    options: {
                        emitCss: true,
                        hotReload: true,
                        onwarn: onwarn,
                        preprocess: require('svelte-preprocess')({
                            scss: {
                                importer: [
                                    scssAliases(aliases),
                                    //magicImporter()
                                ],
                            }
                        })
                    }
                }
            },
```
You can probably disable the `scssAliases` importer as magic importer should do the same thing. You can also see that i have configured standard sass files to use the magic importer under `webpack.dev.js` and this works

**Comment by nitro52** [comment]
Thought it might be a node version issue, i was on 10 so i upgraded to 12 but still get the issue

**Comment by derz** [comment]
@kaisermann  `node-sass-magic-importer` is using node-sass `importer` functions to transformer imports to something else, `svelte-preprocess` is however afterwards using `stats.includedFiles` to determine which files should be watched by rollup (https://github.com/kaisermann/svelte-preprocess/blob/master/src/transformers/scss.ts#L43). But as per https://sass-lang.com/documentation/js-api#result-stats-includedfiles `includedFiles` also contains the raw strings (for example a glob pattern etc.), therefore we're passing files which don't exist as dependencies.

I'm not quite sure how to fix that - there seems to be no way in node-sass to determine which files are getting imported and in the preprocess we don't know, what happens in/via importers... the cleanest way would probably be to fix that in svelte and check if it is a valid file before "watching" it...? Any other ideas?

**Comment by nitro52** [comment]
i think webpack's sass-loader might also wrap the sass importer?

**Comment by ericol** [comment]
@ryburn52 I'm not completely sure your template works for testing this issue.

In your template, the problem is that `~@styles` is trying to load from `node_modules/@styles/package.json`

I take it that `@styles` is trying to reference [this](https://github.com/ryburn52/svelte-typescript-sass-template/blob/4caf6dc11906f84cbcbb8c77f5dee1d0dc7aa856/webpack.parts.js#L50) (Not really sure, as I have no experience with Webpack), but the `~` prefix makes `node-sass-magic-importer` think that you are referencing a module.

I did a test with Bootstrap by running `npm install bootstrap` and then adding `@import '~bootstrap';` in the `style` part of `App.svelte`, removing the `~@style` lines from the two files that reference it, and it worked. (It actually failed, but it's complaining about missing `sass` variables).

Even more so, the problem `node-sass-magic-importer` is having is not related to `svelte-preprocess` (As I was able to reproduce the problem using just `node`, `sass`, `node-sass` and `node-sass-magic-importer`)

Hope this helps. Have a nice day y'all.

**Comment by ryburn52** [comment]
@ericol sounds like you could be onto something. I think one of the issues i had was the the import syntax was slightly different for importing within a sass file verse a style tag in a svelte file. 

It's been a while since i looked at it. We just worked around it for now. I'm interested in how you debugged this though? the node errors don't tend to give you much help.
